;(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define('cfxnes', [], function() {
      return factory({}).cfxnes;
    });
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory({}).cfxnes;
  } else {
    factory(root);
  }
}(this, function(root) {
  // Compiler output [start]
  'use strict';var c;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function f(a){var b='undefined'!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ba(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d}function ca(a){return a instanceof Array?a:ba(f(a))}var da='function'==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if('function'==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={Yd:!0},ia={};try{ia.__proto__=ha;fa=ia.Yd;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+' is not extensible');return a}:null}var ja=ea;
function g(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var d in b)if('prototype'!=d)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};function k(a){if('number'===typeof a)return 1024>Math.abs(a)?a+' B':1048576>Math.abs(a)?~~(a/1024*1E3)/1E3+' KB':~~(a/1048576*1E3)/1E3+' MB'}function n(a){var b=typeof a;if('string'===b)return 80<a.length?'"'+a.substr(0,80)+'..."':'"'+a+'"';if('function'===b)return b=ka(a.constructor),(a=ka(a))?b+'('+a+')':b;if(a&&'object'===b){b=ka(a.constructor);if('Object'===b)return b;a=a.length;return null!=a?b+'('+a+')':b}return String(a)}var la=/function ([^(]+)/;
function ka(a){return a.name?a.name:(a=a.toString().match(la))&&a[1]?a[1]:''};var ma={},na=(ma.S0=[0,0,0,0],ma.S1=[1,1,1,1],ma.S2=[2,2,2,2],ma.S3=[3,3,3,3],ma.H=[0,0,1,1],ma.V=[0,1,0,1],ma['4S']=[0,1,2,3],ma);var oa={pc:60,$d:1789773,Xc:!0,kb:[7457,7456,7458,7457,1,1],lb:[7457,7456,7458,7458,7452,1],Tc:[4,8,16,32,64,96,128,160,202,254,380,508,762,1016,2034,4068],Hc:[428,380,340,320,286,254,226,214,190,160,142,128,106,84,72,54]},pa={pc:50,$d:1491477.5,Xc:!1,kb:[8313,8314,8312,8313,1,1],lb:[8313,8314,8312,8314,8312,1],Tc:[4,8,14,30,60,88,118,148,188,236,354,472,708,944,1890,3778],Hc:[398,354,316,298,276,236,210,198,176,148,132,118,98,78,66,50]};
function qa(a){switch(a){case 'NTSC':return oa;case 'PAL':return pa;default:throw Error('Invalid region: '+n(a));}};var ra={},sa=(ra.off=0,ra.error=1,ra.warn=2,ra.info=3,ra);function ta(){this.c=console;this.priority=0;this.f='off'}ta.prototype.g=function(a){var b=sa[a];if(null==b)throw Error('Invalid log level: '+n(a));this.priority=b;this.f=a};ta.prototype.h=function(){return this.f};ta.prototype.error=function(a,b){1<=this.priority&&this.c.error(a,b)};function ua(a){var b=y;2<=b.priority&&b.c.warn(a)}function A(a){var b=y;3<=b.priority&&b.c.info(a)}var y=new ta;function va(){A('Initializing CPU memory');this.g=new Uint8Array(2048);this.ka=this.Qa=null;this.sc=new Uint32Array(4);this.Pb=0;this.c=[null,null,null];this.f=0;this.M=this.ca=this.o=this.u=null}c=va.prototype;c.connect=function(a){A('Connecting CPU memory');this.u=a.u;this.o=a.o;this.ca=a.ca};c.za=function(a){this.ka=(this.M=a)&&a.ka;this.Qa=a&&a.Qa};c.reset=function(){A('Resetting CPU memory');this.g.fill(0);this.Pb=this.f=0;this.sc.fill(0)};
c.read=function(a){return 32768<=a?this.Qa[this.sc[(a&24576)>>>13]|a&8191]:8192>a?this.g[a&2047]:16416>a?wa(this,a):24576<=a?this.ka&&this.M.ic?this.ka[this.Pb|a&8191]:0:0};
c.write=function(a,b){if(32768<=a)this.M.write(a,b);else if(8192>a)this.g[a&2047]=b;else if(16416>a)switch(16384>a?a&8199:a){case 8192:a=this.u;var d=a.ub;xa(a,b);a.g=a.g&62463|(b&3)<<10;!a.na||d||!a.ub||a.f&524288||(a.R=1);break;case 8193:a=this.u;ya(a,b);a.ua=a.zb[a.Wb];break;case 8195:this.u.Oa=b;break;case 8196:a=this.u;!a.Fb&&(a.ma||a.v)||(a.l[a.Oa]=b);a.Oa=a.Oa+1&255;break;case 8197:a=this.u;a.s=!a.s;a.s?(a.L=b&7,a.g=a.g&65504|b>>>3):a.g=a.g&3103|(b&248)<<2|(b&7)<<12;break;case 8198:this.u.Bc(b);
break;case 8199:a=this.u;!a.Fb&&(a.ma||a.v)||a.C.write(a.c,b);za(a);break;case 16404:this.ca.Bc(b);break;case 16406:Aa(this,b);break;case 16384:Ba(this.o.ea,b);break;case 16385:Ca(this.o.ea,b);break;case 16386:this.o.ea.qa(b);break;case 16387:this.o.ea.pa(b);break;case 16388:Ba(this.o.fa,b);break;case 16389:Ca(this.o.fa,b);break;case 16390:this.o.fa.qa(b);break;case 16391:this.o.fa.pa(b);break;case 16392:Da(this.o.ha,b);break;case 16394:this.o.ha.qa(b);break;case 16395:this.o.ha.pa(b);break;case 16396:Ea(this.o.da,
b);break;case 16398:this.o.da.qa(b);break;case 16399:this.o.da.pa(b);break;case 16400:Fa(this.o.Y,b);break;case 16401:this.o.Y.c=b&127;break;case 16402:this.o.Y.m=49152|(b&255)<<6;break;case 16403:this.o.Y.s=(b&255)<<4|1;break;case 16405:a=this.o;d=a.ea;var e=0!==(b&1);e||(d.f=0);d.l=e;d=a.fa;e=0!==(b&2);e||(d.f=0);d.l=e;d=a.ha;e=0!==(b&4);e||(d.c=0);d.i=e;d=a.da;e=0!==(b&8);e||(d.c=0);d.j=e;Ga(a.Y,0!==(b&16));break;case 16407:Ha(this.o,b),Aa(this,b)}else 24576<=a&&this.ka&&this.M.jc&&(this.ka[this.Pb|
a&8191]=b,this.M.Mc&&this.M.write(a,b))};function wa(a,b){switch(16384>b?b&8199:b){case 8194:return a.u.uc();case 8196:return a=a.u,b=a.l[a.Oa],2===(a.Oa&3)&&(b&=227),b;case 8199:return a=a.u,16128===(a.c&16128)?(b=a.C.read(a.c),a.Hb=a.C.read(a.c&12287),za(a),a=b):(b=a.Hb,a.Hb=a.C.read(a.c),za(a),a=b),a;case 16405:return a.o.uc();case 16406:return Ia(a,1);case 16407:return Ia(a,2);default:return 0}}
c.xc=function(a,b){A((null!=b?'Setting':'Clearing')+' device connected to CPU memory on port #'+a);this.c[a]=b};c.Lb=function(a){return this.c[a]};function Ia(a,b){return(a=a.c[b])?a.read():0}function Aa(a,b){if((b&=1)&&!a.f){var d=a.c[1];d&&d.zc();(d=a.c[2])&&d.zc()}a.f=b};var Ja=[9,1,0,1,0,2,2,13,8,16,8,36,0,0,4,44,9,1,52,3,0,4,0,20,8,58,0,2,0,32,44,8];function Ka(){A('Initializing PPU memory');this.g=null;this.Nb=new Uint32Array(8);this.h=!1;this.c=new Uint8Array(4096);this.f=new Uint32Array(4);this.Xa=new Uint8Array(32);this.M=null}Ka.prototype.za=function(a){this.g=(this.M=a)&&(a.Ka||a.ib);this.h=null!=a&&null!=a.Ka};Ka.prototype.reset=function(){A('Resetting PPU memory');this.Nb.fill(0);this.c.fill(0);La(this,this.M&&this.M.nb||'S0');this.Xa.set(Ja)};
Ka.prototype.read=function(a){a&=16383;return 8192>a?Ma(this,a):16128>a?Na(this,a):this.Xa[Oa(a)]};Ka.prototype.write=function(a,b){a&=16383;8192>a?this.h&&(this.g[this.Nb[(a&7168)>>>10]|a&1023]=b):16128>a?this.c[this.f[(a&3072)>>>10]|a&1023]=b:this.Xa[Oa(a)]=b};function Ma(a,b){return a.g[a.Nb[(b&7168)>>>10]|b&1023]}function Na(a,b){return a.c[a.f[(b&3072)>>>10]|b&1023]}function La(a,b){var d=na[b];if(!d)throw Error('Invalid mirroring: '+n(b));b=d;for(d=0;4>d;d++)a.f[d]=1024*b[d]}
function Oa(a){return a&3?a&31:a&15};function Pa(){A('Initializing DMA');this.f=this.c=0;this.A=null}c=Pa.prototype;c.connect=function(a){A('Connecting DMA');this.A=a.A};c.reset=function(){A('Resetting DMA');this.c=512};c.Bc=function(a){this.c=0;this.f=a<<8};c.w=function(){if(this.Mb()&&(this.c++,this.c&1)){var a=this.A.read(this.f+(this.c>>1));this.A.write(8196,a)}};c.Mb=function(){return 512>this.c};function B(a){A('Initializing mapper');this.nb=a.nb;this.Qa=a.Qa;this.ib=a.ib;this.xa=a.xa;this.Ua=a.Ua;var b=a.ob,d=a.Qb;this.ka=b?new Uint8Array(b):null;this.ob=b;this.Qb=d;this.ic=0<b;this.jc=0<b;this.Mc=!1;b=a.hb;a=a.Jb;this.Ka=b?new Uint8Array(b):null;this.hb=b;this.Jb=a;d?this.l=this.ka.subarray(0,d):a?this.l=this.Ka.subarray(0,a):this.l=null;this.C=this.A=this.u=this.K=null}c=B.prototype;
c.connect=function(a){A('Connecting mapper');this.K=a.K;this.u=a.u;this.A=a.A;this.C=a.C;this.K.za(this);this.A.za(this);this.C.za(this)};c.disconnect=function(){A('Disconnecting mapper');this.C.za(null);this.A.za(null);this.K.za(null);this.K=this.u=this.A=this.C=null};c.reset=function(){A('Resetting mapper');this.ka&&this.ka.fill(0,this.Qb);this.Ka&&this.Ka.fill(0,this.Jb);this.ia()};c.ia=function(){};c.write=function(){};c.w=function(){};function Qa(a,b){Ra(a,0,4*b,4)}
function D(a,b,d){Ra(a,2*b,2*d,2)}function Ra(a,b,d,e){e=void 0===e?1:e;for(var h=a.xa-1>>13,l=0;l<e;l++)a.A.sc[b+l]=8192*(d+l&h)}function Sa(a,b){a.A.Pb=8192*(b&a.ob-1>>13)}function E(a,b){Ta(a,0,8*b,8)}function Ta(a,b,d,e){e=void 0===e?1:e;for(var h=(a.Ua||a.hb)-1>>10,l=0;l<e;l++)a.C.Nb[b+l]=1024*(d+l&h)}c.qc=function(){return this.l};function Ua(a,b){La(a.C,'S'+(void 0===b?0:b))};function Va(){B.apply(this,arguments)}g(Va,B);Va.prototype.ia=function(){Qa(this,0);E(this,0)};Va.prototype.write=function(a,b){Qa(this,b);Ua(this,(b&16)>>>4)};function Wa(){B.apply(this,arguments)}g(Wa,B);Wa.prototype.ia=function(){Qa(this,0);E(this,0)};Wa.prototype.write=function(a,b){Qa(this,b)};function Xa(){B.apply(this,arguments)}g(Xa,B);Xa.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};Xa.prototype.write=function(a,b){E(this,b)};function Ya(){B.apply(this,arguments)}g(Ya,B);Ya.prototype.ia=function(){Qa(this,0);E(this,0)};Ya.prototype.write=function(a,b){Qa(this,b);E(this,b>>>4)};function Za(a){B.call(this,a);this.j=this.f=this.i=this.g=this.h=this.c=0;this.m=(131072===this.xa||262144===this.xa)&&8192===this.ob&&(8192===this.Ua||8192===this.hb)}g(Za,B);Za.prototype.ia=function(){this.h=this.c=0;this.g=12;this.j=this.f=this.i=0;$a(this);ab(this);bb(this);cb(this)};
Za.prototype.write=function(a,b){if(b&128)this.h=this.c=0,this.g|=12;else if(this.c|=(b&1)<<this.h,5<=++this.h){switch(a&57344){case 32768:this.g=this.c;break;case 40960:this.f=this.c;break;case 49152:this.j=this.c;break;case 57344:this.i=this.c}this.h=this.c=0;$a(this);ab(this);bb(this);cb(this)}};function $a(a){switch(a.g&3){case 0:Ua(a,0);break;case 1:Ua(a,1);break;case 2:La(a.C,'V');break;case 3:La(a.C,'H')}}
function ab(a){var b=a.Ka?a.f&16:0,d=a.i&15;switch(a.g&12){case 12:D(a,0,b|d);D(a,1,b|15);break;case 8:D(a,0,b);D(a,1,b|d);break;default:Qa(a,(b|d)>>>1)}}function bb(a){var b=0===(a.f&16);b=0===(a.i&16)&&(!a.m||b);Sa(a,a.Ka?a.f>>>2:0);a.ic=b;a.jc=b}function cb(a){a.g&16?(Ta(a,0,4*a.f,4),Ta(a,4,4*a.j,4)):E(a,a.f>>>1)};function db(a){B.call(this,a);this.g=this.h=this.j=this.i=this.f=this.c=0}g(db,B);db.prototype.ia=function(){D(this,0,0);D(this,1,-1);Sa(this,0);E(this,0);this.g=this.h=this.j=this.i=this.f=this.c=0};
db.prototype.write=function(a,b){switch(a&57345){case 32768:this.c=b;break;case 32769:switch(this.c&7){case 0:case 1:Ta(this,2*((this.c&128)>>>6|this.c&1),2*(b>>>1),2);break;case 2:case 3:case 4:case 5:Ta(this,(~this.c&128)>>>5|this.c-2&3,b);break;case 6:a=(~this.c&64)>>>5;Ra(this,(this.c&64)>>>5,b);Ra(this,a,-2);break;case 7:Ra(this,1,b)}break;case 40960:'4S'!==this.nb&&(b&1?La(this.C,'H'):La(this.C,'V'));break;case 40961:this.ic=128===(b&128);this.jc=128===(b&192);break;case 49152:this.i=b;break;
case 49153:this.f=0;break;case 57344:this.h=!1;eb(this.K,16);break;case 57345:this.h=!0}};db.prototype.w=function(){if(this.u.U&4096){if(!this.g){!this.f||this.j?this.f=this.i:this.f--;if(this.h&&!this.f){var a=this.K;a.g|=16}this.j=!1}this.g=7}else this.g&&this.g--};function fb(a){B.call(this,a);this.Mc=!0}g(fb,B);fb.prototype.ia=function(){Qa(this,0);Sa(this,0);E(this,0)};fb.prototype.write=function(a,b){switch(a){case 32765:Qa(this,b);break;case 32766:Ta(this,0,4*b,4);break;case 32767:Ta(this,4,4*b,4)}};function gb(){B.apply(this,arguments)}g(gb,B);gb.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};function hb(){B.apply(this,arguments)}g(hb,B);hb.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};hb.prototype.write=function(a,b){D(this,0,b)};var H={},ib=(H.AOROM=Va,H.BNROM=Wa,H.CNROM=Xa,H.COLOR_DREAMS=Ya,H.MMC1=Za,H.MMC3=db,H.NINA_001=fb,H.NROM=gb,H.UNROM=hb,H);var jb='LE'===(52===(new Uint8Array((new Uint16Array([4660])).buffer))[0]?'LE':'BE'),mb=jb?kb:lb,pb=jb?nb:ob,qb=mb(0,0,0);function kb(a,b,d,e){return((void 0===e?255:e)<<24|d<<16|b<<8|a)>>>0}function lb(a,b,d,e){return(a<<24|b<<16|d<<8|(void 0===e?255:e))>>>0}function nb(a){return[a&255,a>>>8&255,a>>>16&255,a>>>24&255]}function ob(a){return[a>>>24&255,a>>>16&255,a>>>8&255,a&255]};var rb={'asq-real-a':'YGBgACF7AACcMQCLWQBvbwAxZAAATxEALxkAJykAAEQAADk3ADlPAAAADAwMDAwMrq6uEFbOGyz/YCDsqQC/yhZUyhoInjoEZ1EAQ2EAAHwAAHFTAHGHDAwMDAwMDAwM////RJ7+XGz/mWb/12D//2KV/2RT9JQwwqwAkMQUUtIoIMaSGLrSTExMDAwMDAwM////o8z/pLT/wbb/4Lf//8DF/7yr/9Cf/OCQ4uqYyvKgoOrioOL6tra2DAwMDAwM','asq-real-b':'bGxsACCUAACoPACYcABwfAA8cAAAaBAARhoAPCwAAFAAADxMADpmAAAAEBAQEBAQurq6KljWPDL/gCDwwADA0BR00hokpjweflIAWGQAAIgAAHRoAHKeEBAQEBAQEBAQ////XqD/jIL/xHD//1z//2i8/3J8/JZK2a0AmMYuTtROOsiaLr7cWFhYEBAQEBAQ////xtj/1Mr/8MT//7z//8Tw/8rU/9i+/+am6uyyxvTGuuzqtub/wsLCEBAQEBAQ',
'bmf-fin-r2':'UlJSAACACACKLAB+SgBOUAAGRAAAJggACiAAAC4AADIAACYKABxIAAAAAAAAAAAApKSkADjONBbsXgTcjACwmgBMkBgAcDYATFQADmwAAHQAAGwsAF6EAAAAAAAAAAAA////TJz/fHj/pmT/2lr/8FTA8GpW1oYQuqQAdsAARswaLshmNMK+Ojo6AAAAAAAA////ttr/yMr/2sL/8L7//Lzu+sLA8syi5tqSzOaOuO6iruq+rujisLCwAAAAAAAA','bmf-fin-r3':'aGhoABKZGgiqUQKafgBpjgAcfgMBURgAHzcAAU4AAFoAAFAcAEBhAAAAAAAAAAAAubm5DFzXUDXwiRnguwyzzgxhwCsOlU0BYW8AH4sAAZgMAJNLAIGbAAAAAAAAAAAA////Y7T/m5H/03f/72r/+WjA+X1s7Zstvb0WfNocS+hHNeWRP9ndYGBgAAAAAAAA////rOf/1c3/7br/+LD//rDs/b21+dKO6Ot8u/OCmfeiivXQkvTxvr6+AAAAAAAA',
'fceu-13':'YGBgAAB4FACALABuSgBObAAYWgMCURgANCQAADQAADIAADQgACx4AAAAAgICAgICxMTEAFjeMB/8fxTgqACwwAZcwCsOpkAQb2EAMIAAAHwAAHw8AG6EFBQUBAQEBAQE8PDwTKr/b3P1sHD/2lr/8GDA+INt0JAw1MAwZtAAJt0aLshmNMK+VFRUBgYGBgYG////ttr/yMr/2sL/8L7//Lzu/9C0/9qQ7OyS3PaeuP+iruq+nu/vvr6+CAgICAgI','fceu-15':'YGBgAABwFACALABuSgBObAAYWgMCURgANCQAADQAADIAADQgACx4AAAAAgICAgICxMTEAFjeMB/8fxTgqACwwAZcwCsOpkAQb2EAMIAAAHwAAHw8AG6EFBQUBAQEBAQE8PDwTKr/b3P1sHD/2lr/8GDA+INt0JAw1MAwZtAAJt0aLshmNMK+VFRUBgYGBgYG////ttr/yMr/2sL/8L7//Lzu/9C0/9qQ7OyS3PaeuP+iruq+nu/vvr6+CAgICAgI',
fceux:'dHR0JBiMAACoRACcjAB0qAAQpAAAfAgAQCwAAEQAAFAAADwUGDxcAAAAAAAAAAAAvLy8AHDsIDjsgADwvAC85ABY2CgAyEwMiHAAAJQAAKgAAJA4AICIAAAAAAAAAAAA/Pz8PLz8XJT8zIj89Hj8/HS0/HRg/Jg48Lw8gNAQTNxIWPiYAOjYeHh4AAAAAAAA/Pz8qOT8xNT81Mj8/MT8/MTY/Lyw/Nio/OSg4PygqPC8sPzMnPzwxMTEAAAAAAAA','nestopia-rgb':'bW1tACSSAADbbUnbkgBttgBttiQAkkkAbUkAJEkAAG0kAJIAAElJAAAAAAAAAAAAtra2AG3bAEn/kgD/tgD//wCS/wAA220Akm0AJJIAAJIAALZtAJKSJCQkAAAAAAAA////bbb/kpL/223//wD//23//5IA/7YA29sAbdsAAP8ASf/bAP//SUlJAAAAAAAA////ttv/27b//7b//5L//7a2/9uS//9J//9ttv9Jkv9tSf/bktv/kpKSAAAAAAAA',
'nestopia-yuv':'ZmZmACqIFBKnOwCkXAB+bgBAbAcAVh0AMzUADEgAAFIAAE8IAEBNAAAAAAAAAAAAra2tFV/ZQkD/dSf+oBrMtx57tTEgmU4Aa20AOIcADZMAAI8yAHyNAAAAAAAAAAAA////ZLD/kpD/xnb/8mr//27M/4Fw6p4ivL4AiNgAXOQwReCCSM3eT09PAAAAAAAA////wN//09L/6Mj/+sL//8Tq/8zF99il5OWUz++WvfSrs/PMtevyuLi4AAAAAAAA','sony-cxa2025as':'WFhYACOMABObLQWFXQBSegAXeggAXxgANSoACTkAAD8AADwiADJdAAAAAAAAAAAAoaGhAFPuFTz+YCjkqR2Y1B5B0iwAqkQAbF4ALXMAAH0GAHhSAGmpAAAAAAAAAAAA////H6X+Xon+tXL+/mX2/meQ/nc8/pMIxLIAecoQOtVKEdGkBr/+QkJCAAAAAAAA////oNn+vcz+4cL+/rz7/r3Q/sWp/tGO6d6Gx+mSqO6wlezZkeT+rKysAAAAAAAA',
'unsaturated-v6':'a2trAB6HHwuWOwyHWQ1hXgUoVREARhsAMDIACkgAAE4AAEYZADpYAAAAAAAAAAAAsrKyGlPRSDXucSPsmh63pR5ipS0Zh0sAZ2kAKYQAA4sAAIJAAHiRAAAAAAAAAAAA////Y639kIr+uXf853H+92/J9YNq3ZwpvbgHhNEHW9w7SNd9SMzOVVVVAAAAAAAA////xOP+19X+5s3++cr+/snw/tHH99ys6Oic0fKdv/Sxt/XNt/Duvr6+AAAAAAAA'};
function sb(a){a=void 0===a?'fceux':a;var b=rb[a];if(b){A('Creating "'+a+'" palette');if('undefined'!==typeof window&&'function'===typeof window.atob)a=window.atob(b);else if('function'===typeof Buffer)a=Buffer.from(b,'base64').toString('binary');else throw Error('Unable to decode base64 string');if(192!==a.length)throw Error('Palette data does not contain 64 entries');b=new Uint32Array(64);for(var d=0;64>d;d++){var e=3*d;b[d]=mb(a.charCodeAt(e),a.charCodeAt(e+1),a.charCodeAt(e+2))}return b}throw Error('Invalid palette: '+
n(a));};for(var J=new Uint32Array(262),M=0;M<J.length;M++){239>=M&&(J[M]|=2,J[M]|=512,J[M]|=2048,J[M]|=1024);if(239>=M||261===M)J[M]|=4,J[M]|=8,J[M]|=16,J[M]|=32,J[M]|=64,J[M]|=128,J[M]|=256,J[M]|=8192,J[M]|=16384,J[M]|=32768;if(7>=M||232<=M&&239>=M)J[M]|=4096}J[241]|=131072;J[241]|=262144;J[261]|=65536;J[261]|=524288;J[261]|=1048576;
for(var N=new Uint32Array(341),P=0;P<N.length;P++){1<=P&&256>=P&&(N[P]|=2,N[P]|=4096);if(1===(P&7)||339===P)N[P]|=4;3===(P&7)&&339!==P&&(N[P]|=8);5===(P&7)&&(N[P]|=256>=P||321<=P?16:64);7===(P&7)&&(N[P]|=256>=P||321<=P?32:128);if(0===(P&7)&&8<=P&&256>=P||328===P||336===P)N[P]|=8192;if(1===(P&7)&&9<=P&&257>=P||329===P||337===P)N[P]|=256;if(1<=P&&256>=P||321<=P&&336>=P)N[P]|=512;280<=P&&304>=P&&(N[P]|=65536);1<=P&&8>=P&&(N[P]|=2048);1<=P&&3>=P&&(N[P]|=262144)}N[1]|=131072;N[1]|=524288;N[65]|=1024;
N[256]|=16384;N[257]|=32768;N[338]|=1048576;function tb(){this.x=0;this.Nc=this.ad=!1;this.Uc=0;this.Pc=!1;this.Wc=this.Vc=this.Pa=0};function ub(){A('Initializing PPU');this.h=261;this.f=this.i=0;this.wb=!1;this.U=0;this.vb=this.Gb=this.Fb=this.Rc=!1;this.R=0;this.j=null;this.Kb=!1;this.O=0;this.Lc=null;this.zb=Array(8);this.ua=null;this.la=this.m=0;this.ab=Array(261);this.Db=new Uint8Array(261);this.l=new Uint8Array(256);this.$=Array(8);this.Hb=this.c=this.g=this.Oa=0;this.s=!1;this.na=this.Eb=this.Bb=this.Wb=this.ma=this.v=this.Sc=this.Jc=this.ub=this.dc=this.Oc=this.Ab=this.Qc=this.Pa=this.lc=this.hc=this.oc=this.nc=this.gc=
this.ec=this.yb=this.xb=this.S=this.P=this.L=0;this.C=this.K=null}c=ub.prototype;c.connect=function(a){A('Connecting PPU');this.K=a.K;this.C=a.C};
c.reset=function(){A('Resetting PPU');this.l.fill(0);for(var a=0;a<this.$.length;a++)this.$[a]=new tb;xa(this,0);ya(this,0);this.Hb=this.c=this.g=this.Oa=this.na=this.Eb=this.Bb=0;this.s=!1;this.lc=this.hc=this.oc=this.nc=this.gc=this.ec=this.yb=this.xb=this.S=this.P=this.L=0;this.h=261;this.f=this.i=0;this.vb=this.Gb=!1;this.R=0;this.wb=!1;this.la=this.m=0;this.ab.fill(null);this.Db.fill(0)};c.Ra=function(a){A('Setting PPU region parameters');this.Rc=a.Xc};
function xa(a,b){a.Qc=b>>>2&1;a.Ab=b<<9&4096;a.Oc=b<<8&4096;a.dc=b>>>5&1;a.ub=b>>>7}function ya(a,b){a.Jc=~b>>>1&1;a.Sc=~b>>>2&1;a.v=b>>>3&1;a.ma=b>>>4&1;a.Wb=b>>>5&7}c.uc=function(){var a=this.Bb<<5|this.Eb<<6|this.na<<7;this.na=0;this.s=!1;this.f&131072&&(this.Gb=!0);this.f&262144&&(this.vb=!0);return a};c.Bc=function(a){(this.s=!this.s)?this.g=this.g&255|(a&63)<<8:this.c=this.g=this.g&65280|a};function za(a){a.c=a.c+(a.Qc?32:1)&65535}
c.w=function(){if(this.ma||this.v){if(this.f&4)this.U=8192|this.c&4095,this.Pa=this.Oc+(Na(this.C,this.U)<<4)+(this.c>>>12&7);else if(this.f&8){this.U=(9152|this.c&3072)+(this.c>>>4&56|this.c>>>2&7);var a=Na(this.C,this.U)>>>(this.c>>>4&4|this.c&2)&3;this.hc=a&1;this.lc=a>>>1&1}else this.f&16?(this.U=this.Pa,this.nc=Ma(this.C,this.U)):this.f&32?(this.U=this.Pa+8,this.oc=Ma(this.C,this.U)):this.f&64?this.la<this.m?(a=this.$[this.la],this.U=a.Pa,a.Vc=Ma(this.C,this.U)):this.U=this.Ab|4080:this.f&128&&
(this.la<this.m?(a=this.$[this.la++],this.U=a.Pa+8,a.Wc=Ma(this.C,this.U)):this.U=this.Ab|4080);if(this.f&1024){this.m=this.la=0;a=this.dc?16:8;for(var b=this.h+1,d=b-a+1,e=0;e<this.l.length;e+=4){var h=this.l[e]+1;if(!(h<d||h>b)){if(8<=this.m){this.Bb=1;break}var l=this.Ab,m=this.l[e+1];this.dc&&(l=(m&1)<<12,m&=254);var p=this.l[e+2];h=b-h;p&128&&(h=a-h-1);8<=h&&(h-=8,m++);var r=this.$[this.m];r.x=this.l[e+3];r.ad=0===e;r.Nc=p&64;r.Uc=16|(p&3)<<2;r.Pc=0===(p&32);r.Pa=l+(m<<4)+h;this.m++}}}this.f&
256&&(this.P|=this.nc,this.S|=this.oc,this.ec=this.hc,this.gc=this.lc);this.f&2&&(a=!this.v||this.Jc&&this.f&2048?0:this.yb<<this.L>>4&8|this.xb<<this.L>>5&4|this.S<<this.L>>14&2|this.P<<this.L>>15&1,b=!this.ma||this.Sc&&this.f&2048?0:this.Db[this.i],a&3?b&3&&(d=this.ab[this.i],d.ad&&256!==this.i&&(this.Eb=1),d.Pc&&(a=b)):a=b&3?b:0,this.Rc&&this.f&4096?this.j[this.O++]=qb:(a=this.C.Xa[Oa(a)],this.j[this.O++]=this.ua[a&63]));this.f&512&&(this.P<<=1,this.S<<=1,this.xb=this.xb<<1|this.ec,this.yb=this.yb<<
1|this.gc);this.f&8192&&(31===(this.c&31)?(this.c&=65504,this.c^=1024):this.c+=1);this.f&16384&&(28672===(this.c&28672)?(this.c&=4095,992===(this.c&992)?this.c&=64543:928===(this.c&992)?(this.c&=64543,this.c^=2048):this.c+=32):this.c+=4096);this.f&32768&&(this.c=this.c&31712|this.g&1055);this.f&65536&&(this.c=this.c&1055|this.g&31712)}else this.f&2&&(this.j[this.O++]=qb),this.U=this.c;this.R&&(this.ub?--this.R||this.vb||(a=this.K,a.g|=2):this.R=0);this.f&131072?(this.Gb||(this.na=1),this.Kb=this.Fb=
!0,this.R=2):this.f&524288&&(this.Fb=!1,this.na=0,this.vb=this.Gb=!1,this.Bb=this.Eb=0);this.f&1048576&&this.wb&&(this.ma||this.v)&&this.i++;this.i++;if(340<this.i&&(this.i=0,this.h++,261<this.h&&(this.h=0,this.wb=!this.wb,this.O=0),239>=this.h&&(this.ab.fill(null),this.Db.fill(0),0<this.h)))for(a=0;a<this.m;a++)for(b=this.$[a],d=0;8>d;d++){e=b.x+d+1;if(256<e)break;!this.ab[e]&&(l=b.Nc?d:d^7,l=(b.Wc>>>l&1)<<1|b.Vc>>>l&1)&&(this.ab[e]=b,this.Db[e]=b.Uc|l)}this.f=J[this.h]&N[this.i]};
c.vc=function(){for(var a=0;16>a;a++)for(var b=a<<3,d=0;32>d;d++)for(var e=d<<3,h=((d&16)<<4|a<<4|d&15)<<4,l=0;8>l;l++)for(var m=b+l,p=Ma(this.C,h+l),r=Ma(this.C,h+l+8),q=0;8>q;q++){var F=q^7;this.j[256*m+(e+q)]=this.ua[this.C.Xa[Oa((r>>F&1)<<1|p>>F&1)]&63]}for(a=0;4>a;a++)for(b=28*a+128,d=0;8>d;d++)for(e=d<<5,h=this.C.Xa[Oa(a<<3|d)],l=b;l<b+28;l++)for(m=e;m<e+32;m++)this.j[256*l+m]=this.ua[h&63]};var Q=Array(255);function vb(){A('Initializing CPU');this.P=!1;this.L=this.s=this.R=this.m=this.O=this.j=this.l=this.h=this.c=this.i=this.f=this.$=this.v=this.g=this.S=0;this.o=this.u=this.ca=this.A=this.M=null}c=vb.prototype;c.connect=function(a){A('Connecting CPU');this.A=a.A;this.u=a.u;this.o=a.o;this.ca=a.ca};c.za=function(a){this.M=a};
c.reset=function(){A('Resetting CPU');this.g=0;this.P=!1;this.l=this.h=this.c=this.i=0;wb(this,0);for(var a=0;8>a;a++)this.A.write(a,255);this.A.write(8,247);this.A.write(9,239);this.A.write(10,223);this.A.write(15,191);for(a=16;2048>a;a++)this.A.write(a,255);for(a=16384;16400>a;a++)this.A.write(a,0);xb(this)};
c.step=function(){var a=this.ca.Mb()||this.o.Mb();if(this.g&&!a)a:{if(this.g&1)xb(this);else if(this.g&2)yb(this,this.f),zb(this,Ab(this)),this.m=1,this.f=Bb(this,65530),eb(this,2);else{if(this.v)break a;yb(this,this.f);zb(this,Ab(this));this.m=1;this.f=Bb(this,65534)}this.w();this.w()}if(this.P||a)this.w();else if(a=Q[Cb(this)]){this.v=this.m;this.S=a[2];var b=f(a);a=b.next().value;b=b.next().value.call(this);a.call(this,b)}else ua('CPU halted!'),this.P=!0};
function xb(a){R(a,16405,0);R(a,16407,a.o.Ic);a.i=a.i-3&255;a.m=1;a.f=Bb(a,65532);eb(a,1);a.w();a.P=!1}function Cb(a){return S(a,Db(a,1))}function Db(a,b){var d=a.f;a.f=a.f+b&65535;return d}function S(a,b){a.w();return a.A.read(b)}function Bb(a,b){var d=b+1&65535;b=S(a,b);return S(a,d)<<8|b}function Eb(a,b){var d=b&65280|b+1&255;b=S(a,b);return S(a,d)<<8|b}function R(a,b,d){a.w();a.A.write(b,d);return d}function Fb(a,b){var d=S(a,b);return R(a,b,d)}function zb(a,b){R(a,256+a.i,b);a.i=a.i-1&255}
function yb(a,b){zb(a,b>>>8);zb(a,b&255)}function Gb(a){a.i=a.i+1&255;return S(a,256+a.i)}function Ab(a){return a.j|a.O<<1|a.m<<2|a.R<<3|32|a.s<<6|a.L<<7}function wb(a,b){a.j=b&1;a.O=b>>>1&1;a.m=b>>>2&1;a.R=b>>>3&1;a.s=b>>>6&1;a.L=b>>>7}function eb(a,b){a.g&=~b}c.w=function(){2<this.o.Y.h||(this.ca.w(),this.M.w());this.u.w();this.u.w();this.u.w();this.o.w()};c.F=function(){this.w()};c.Ib=function(){this.w()};c.N=function(){return Db(this,1)};c.D=function(){return Cb(this)};
c.G=function(){var a=Cb(this),b=this.h;S(this,a);return a+b&255};c.Vb=function(){var a=Cb(this),b=this.l;S(this,a);return a+b&255};c.B=function(){return Bb(this,Db(this,2))};c.J=function(){return Hb(this,Bb(this,Db(this,2)),this.h)};c.T=function(){return Hb(this,Bb(this,Db(this,2)),this.l)};c.ya=function(){var a=Cb(this);return this.f+(a&128?a-256:a)&65535};c.ge=function(){return Eb(this,Bb(this,Db(this,2)))};c.W=function(){return Eb(this,this.G())};
c.X=function(){var a=Eb(this,Cb(this));return Hb(this,a,this.l)};function Hb(a,b,d){d=b+d&65535;a.$=(b&65280)!==(d&65280);(a.S&2||a.$)&&S(a,b&65280|d&255);return d}c.I=function(){this.S&1&&this.w()};c.qd=function(){this.j=0};c.sd=function(){this.v=this.m;this.m=0};c.rd=function(){this.R=0};c.td=function(){this.s=0};c.Hd=function(){this.j=1};c.Jd=function(){this.v=this.m;this.m=1};c.Id=function(){this.R=1};c.Ja=function(a){R(this,a,this.c)};c.ac=function(a){R(this,a,this.h)};
c.Cb=function(a){R(this,a,this.c&this.h)};c.bc=function(a){R(this,a,this.l)};c.$b=function(a){Ib(this,a,this.c&this.h)};c.Kd=function(a){Ib(this,a,this.h)};c.Ld=function(a){Ib(this,a,this.l)};c.va=function(a){T(this,S(this,a))};c.bb=function(a){Jb(this,S(this,a))};c.cb=function(a){a=S(this,a);Kb(this,a);this.l=a};c.Ca=function(a){a=S(this,a);T(this,a);Jb(this,a)};c.Ad=function(a){this.i&=S(this,a);T(this,this.i);Jb(this,this.i)};c.Pd=function(){Jb(this,this.c)};
c.Qd=function(){var a=this.c;Kb(this,a);this.l=a};c.Sd=function(){T(this,this.h)};c.Ud=function(){T(this,this.l)};c.Rd=function(){Jb(this,this.i)};c.Td=function(){this.i=this.h};c.Bd=function(){zb(this,this.c)};c.Cd=function(){zb(this,Ab(this)|16)};c.Dd=function(){this.w();T(this,Gb(this))};c.Ed=function(){this.w();this.v=this.m;wb(this,Gb(this))};c.ba=function(a){return T(this,this.c&S(this,a))};c.wa=function(a){T(this,this.c|S(this,a))};c.ta=function(a){T(this,this.c^S(this,a))};
c.Ec=function(a){a=S(this,a);this.O=!(this.c&a)|0;this.s=a>>>6&1;this.L=a>>>7};c.$a=function(a){return Lb(this,a,Fb(this,a)+1&255)};c.wd=function(){Jb(this,this.h+1&255)};c.xd=function(){var a=this.l+1&255;Kb(this,a);this.l=a};c.Za=function(a){return Lb(this,a,Fb(this,a)-1&255)};c.ud=function(){Jb(this,this.h-1&255)};c.vd=function(){var a=this.l-1&255;Kb(this,a);this.l=a};c.sa=function(a){Mb(this,this.c,S(this,a))};c.Xb=function(a){Mb(this,this.h,S(this,a))};
c.Yb=function(a){Mb(this,this.l,S(this,a))};c.gd=function(a){Nb(this,!this.j,a)};c.hd=function(a){Nb(this,this.j,a)};c.ld=function(a){Nb(this,!this.O,a)};c.jd=function(a){Nb(this,this.O,a)};c.od=function(a){Nb(this,!this.s,a)};c.pd=function(a){Nb(this,this.s,a)};c.md=function(a){Nb(this,!this.L,a)};c.kd=function(a){Nb(this,this.L,a)};c.Fc=function(a){this.f=a};c.zd=function(a){this.w();yb(this,this.f-1&65535);this.f=a};c.Gd=function(){this.w();this.w();this.f=(Gb(this)|Gb(this)<<8)+1&65535};
c.nd=function(){Db(this,1);yb(this,this.f);zb(this,Ab(this)|16);this.m=this.v=1;this.f=Bb(this,this.g&2?65530:65534)};c.Fd=function(){this.w();wb(this,Gb(this));this.v=this.m;this.f=Gb(this)|Gb(this)<<8};c.ra=function(a){Ob(this,S(this,a))};c.oa=function(a){Ob(this,S(this,a)^255)};c.Sa=function(a){return Pb(this,a,this.wc,!1)};c.Da=function(a){return Pb(this,a,this.Yc,!1)};c.Ta=function(a){return Pb(this,a,this.wc,!0)};c.Fa=function(a){return Pb(this,a,this.Yc,!0)};
c.Aa=function(a){Mb(this,this.c,this.Za(a))};c.Ba=function(a){Ob(this,this.$a(a)^255)};c.Ha=function(a){T(this,this.c|this.Sa(a))};c.Ia=function(a){T(this,this.c^this.Da(a))};c.Ea=function(a){T(this,this.c&this.Ta(a))};c.Xd=function(a){T(this,this.h&this.ba(a))};c.Ga=function(a){Ob(this,this.Fa(a))};c.dd=function(a){this.h=Mb(this,this.c&this.h,S(this,a))};c.Cc=function(a){this.wc(this.ba(a),!1)};c.bd=function(a){this.ba(a);this.Da(null)};
c.cd=function(a){this.ba(a);this.Fa(null);this.j=this.c>>>6&1;this.s=this.c>>>5&1^this.j};c.Od=function(a){this.i=this.c&this.h;this.$b(a)};function T(a,b){Kb(a,b);return a.c=b}function Jb(a,b){Kb(a,b);a.h=b}function Lb(a,b,d){Kb(a,d);return R(a,b,d)}function Ib(a,b,d){a.$?R(a,b,a.A.read(b)):R(a,b,d&(b>>>8)+1)}function Ob(a,b){var d=a.c+b+a.j;a.j=d>>>8&1;a.s=((a.c^d)&(b^d))>>>7&1;T(a,d&255)}function Mb(a,b,d){b-=d;a.j=0<=b|0;Kb(a,b);return b&255}
function Nb(a,b,d){b&&(a.w(),(a.f&65280)!==(d&65280)&&a.w(),a.f=d)}function Pb(a,b,d,e){if(null!=b)return d=d.call(a,Fb(a,b),e),Lb(a,b,d);b=d.call(a,a.c,e);return T(a,b)}c.wc=function(a,b){b&=this.j;this.j=a>>>7;return(a<<1|b)&255};c.Yc=function(a,b){b=(b&this.j)<<7;this.j=a&1;return a>>>1|b};function Kb(a,b){a.O=!(b&255)|0;a.L=b>>>7&1}var U=vb.prototype;Q[26]=[U.I,U.F,0];Q[58]=[U.I,U.F,0];Q[90]=[U.I,U.F,0];Q[122]=[U.I,U.F,0];Q[218]=[U.I,U.F,0];Q[234]=[U.I,U.F,0];Q[250]=[U.I,U.F,0];
Q[128]=[U.I,U.N,1];Q[130]=[U.I,U.N,1];Q[137]=[U.I,U.N,1];Q[194]=[U.I,U.N,1];Q[226]=[U.I,U.N,1];Q[4]=[U.I,U.D,1];Q[68]=[U.I,U.D,1];Q[100]=[U.I,U.D,1];Q[20]=[U.I,U.G,1];Q[52]=[U.I,U.G,1];Q[84]=[U.I,U.G,1];Q[116]=[U.I,U.G,1];Q[212]=[U.I,U.G,1];Q[244]=[U.I,U.G,1];Q[12]=[U.I,U.B,1];Q[28]=[U.I,U.J,1];Q[60]=[U.I,U.J,1];Q[92]=[U.I,U.J,1];Q[124]=[U.I,U.J,1];Q[220]=[U.I,U.J,1];Q[252]=[U.I,U.J,1];Q[24]=[U.qd,U.F,0];Q[88]=[U.sd,U.F,0];Q[216]=[U.rd,U.F,0];Q[184]=[U.td,U.F,0];Q[56]=[U.Hd,U.F,0];
Q[120]=[U.Jd,U.F,0];Q[248]=[U.Id,U.F,0];Q[133]=[U.Ja,U.D,0];Q[149]=[U.Ja,U.G,0];Q[141]=[U.Ja,U.B,0];Q[157]=[U.Ja,U.J,2];Q[153]=[U.Ja,U.T,2];Q[129]=[U.Ja,U.W,0];Q[145]=[U.Ja,U.X,2];Q[134]=[U.ac,U.D,0];Q[150]=[U.ac,U.Vb,0];Q[142]=[U.ac,U.B,0];Q[135]=[U.Cb,U.D,0];Q[151]=[U.Cb,U.Vb,0];Q[143]=[U.Cb,U.B,0];Q[131]=[U.Cb,U.W,0];Q[132]=[U.bc,U.D,0];Q[148]=[U.bc,U.G,0];Q[140]=[U.bc,U.B,0];Q[147]=[U.$b,U.X,2];Q[159]=[U.$b,U.T,2];Q[158]=[U.Kd,U.T,2];Q[156]=[U.Ld,U.J,2];Q[169]=[U.va,U.N,0];Q[165]=[U.va,U.D,0];
Q[181]=[U.va,U.G,0];Q[173]=[U.va,U.B,0];Q[189]=[U.va,U.J,0];Q[185]=[U.va,U.T,0];Q[161]=[U.va,U.W,0];Q[177]=[U.va,U.X,0];Q[162]=[U.bb,U.N,0];Q[166]=[U.bb,U.D,0];Q[182]=[U.bb,U.Vb,0];Q[174]=[U.bb,U.B,0];Q[190]=[U.bb,U.T,0];Q[160]=[U.cb,U.N,0];Q[164]=[U.cb,U.D,0];Q[180]=[U.cb,U.G,0];Q[172]=[U.cb,U.B,0];Q[188]=[U.cb,U.J,0];Q[171]=[U.Ca,U.N,0];Q[167]=[U.Ca,U.D,0];Q[183]=[U.Ca,U.Vb,0];Q[175]=[U.Ca,U.B,0];Q[191]=[U.Ca,U.T,0];Q[163]=[U.Ca,U.W,0];Q[179]=[U.Ca,U.X,0];Q[187]=[U.Ad,U.T,0];Q[170]=[U.Pd,U.F,0];
Q[168]=[U.Qd,U.F,0];Q[138]=[U.Sd,U.F,0];Q[152]=[U.Ud,U.F,0];Q[154]=[U.Td,U.F,0];Q[186]=[U.Rd,U.F,0];Q[72]=[U.Bd,U.F,0];Q[8]=[U.Cd,U.F,0];Q[104]=[U.Dd,U.F,0];Q[40]=[U.Ed,U.F,0];Q[41]=[U.ba,U.N,0];Q[37]=[U.ba,U.D,0];Q[53]=[U.ba,U.G,0];Q[45]=[U.ba,U.B,0];Q[61]=[U.ba,U.J,0];Q[57]=[U.ba,U.T,0];Q[33]=[U.ba,U.W,0];Q[49]=[U.ba,U.X,0];Q[9]=[U.wa,U.N,0];Q[5]=[U.wa,U.D,0];Q[21]=[U.wa,U.G,0];Q[13]=[U.wa,U.B,0];Q[29]=[U.wa,U.J,0];Q[25]=[U.wa,U.T,0];Q[1]=[U.wa,U.W,0];Q[17]=[U.wa,U.X,0];Q[73]=[U.ta,U.N,0];
Q[69]=[U.ta,U.D,0];Q[85]=[U.ta,U.G,0];Q[77]=[U.ta,U.B,0];Q[93]=[U.ta,U.J,0];Q[89]=[U.ta,U.T,0];Q[65]=[U.ta,U.W,0];Q[81]=[U.ta,U.X,0];Q[36]=[U.Ec,U.D,0];Q[44]=[U.Ec,U.B,0];Q[230]=[U.$a,U.D,0];Q[246]=[U.$a,U.G,0];Q[238]=[U.$a,U.B,0];Q[254]=[U.$a,U.J,2];Q[232]=[U.wd,U.F,0];Q[200]=[U.xd,U.F,0];Q[198]=[U.Za,U.D,0];Q[214]=[U.Za,U.G,0];Q[206]=[U.Za,U.B,0];Q[222]=[U.Za,U.J,2];Q[202]=[U.ud,U.F,0];Q[136]=[U.vd,U.F,0];Q[201]=[U.sa,U.N,0];Q[197]=[U.sa,U.D,0];Q[213]=[U.sa,U.G,0];Q[205]=[U.sa,U.B,0];
Q[221]=[U.sa,U.J,0];Q[217]=[U.sa,U.T,0];Q[193]=[U.sa,U.W,0];Q[209]=[U.sa,U.X,0];Q[224]=[U.Xb,U.N,0];Q[228]=[U.Xb,U.D,0];Q[236]=[U.Xb,U.B,0];Q[192]=[U.Yb,U.N,0];Q[196]=[U.Yb,U.D,0];Q[204]=[U.Yb,U.B,0];Q[144]=[U.gd,U.ya,0];Q[176]=[U.hd,U.ya,0];Q[208]=[U.ld,U.ya,0];Q[240]=[U.jd,U.ya,0];Q[80]=[U.od,U.ya,0];Q[112]=[U.pd,U.ya,0];Q[16]=[U.md,U.ya,0];Q[48]=[U.kd,U.ya,0];Q[76]=[U.Fc,U.B,0];Q[108]=[U.Fc,U.ge,0];Q[32]=[U.zd,U.B,0];Q[96]=[U.Gd,U.F,0];Q[0]=[U.nd,U.F,0];Q[64]=[U.Fd,U.F,0];Q[105]=[U.ra,U.N,0];
Q[101]=[U.ra,U.D,0];Q[117]=[U.ra,U.G,0];Q[109]=[U.ra,U.B,0];Q[125]=[U.ra,U.J,0];Q[121]=[U.ra,U.T,0];Q[97]=[U.ra,U.W,0];Q[113]=[U.ra,U.X,0];Q[233]=[U.oa,U.N,0];Q[235]=[U.oa,U.N,0];Q[229]=[U.oa,U.D,0];Q[245]=[U.oa,U.G,0];Q[237]=[U.oa,U.B,0];Q[253]=[U.oa,U.J,0];Q[249]=[U.oa,U.T,0];Q[225]=[U.oa,U.W,0];Q[241]=[U.oa,U.X,0];Q[10]=[U.Sa,U.Ib,0];Q[6]=[U.Sa,U.D,0];Q[22]=[U.Sa,U.G,0];Q[14]=[U.Sa,U.B,0];Q[30]=[U.Sa,U.J,2];Q[74]=[U.Da,U.Ib,0];Q[70]=[U.Da,U.D,0];Q[86]=[U.Da,U.G,0];Q[78]=[U.Da,U.B,0];
Q[94]=[U.Da,U.J,2];Q[42]=[U.Ta,U.Ib,0];Q[38]=[U.Ta,U.D,0];Q[54]=[U.Ta,U.G,0];Q[46]=[U.Ta,U.B,0];Q[62]=[U.Ta,U.J,2];Q[106]=[U.Fa,U.Ib,0];Q[102]=[U.Fa,U.D,0];Q[118]=[U.Fa,U.G,0];Q[110]=[U.Fa,U.B,0];Q[126]=[U.Fa,U.J,2];Q[199]=[U.Aa,U.D,0];Q[215]=[U.Aa,U.G,0];Q[207]=[U.Aa,U.B,0];Q[223]=[U.Aa,U.J,2];Q[219]=[U.Aa,U.T,2];Q[195]=[U.Aa,U.W,0];Q[211]=[U.Aa,U.X,2];Q[231]=[U.Ba,U.D,0];Q[247]=[U.Ba,U.G,0];Q[239]=[U.Ba,U.B,0];Q[255]=[U.Ba,U.J,2];Q[251]=[U.Ba,U.T,2];Q[227]=[U.Ba,U.W,0];Q[243]=[U.Ba,U.X,2];
Q[7]=[U.Ha,U.D,0];Q[23]=[U.Ha,U.G,0];Q[15]=[U.Ha,U.B,0];Q[31]=[U.Ha,U.J,2];Q[27]=[U.Ha,U.T,2];Q[3]=[U.Ha,U.W,0];Q[19]=[U.Ha,U.X,2];Q[71]=[U.Ia,U.D,0];Q[87]=[U.Ia,U.G,0];Q[79]=[U.Ia,U.B,0];Q[95]=[U.Ia,U.J,2];Q[91]=[U.Ia,U.T,2];Q[67]=[U.Ia,U.W,0];Q[83]=[U.Ia,U.X,2];Q[39]=[U.Ea,U.D,0];Q[55]=[U.Ea,U.G,0];Q[47]=[U.Ea,U.B,0];Q[63]=[U.Ea,U.J,2];Q[59]=[U.Ea,U.T,2];Q[35]=[U.Ea,U.W,0];Q[51]=[U.Ea,U.X,2];Q[139]=[U.Xd,U.N,0];Q[103]=[U.Ga,U.D,0];Q[119]=[U.Ga,U.G,0];Q[111]=[U.Ga,U.B,0];Q[127]=[U.Ga,U.J,2];
Q[123]=[U.Ga,U.T,2];Q[99]=[U.Ga,U.W,0];Q[115]=[U.Ga,U.X,2];Q[203]=[U.dd,U.N,0];Q[11]=[U.Cc,U.N,0];Q[43]=[U.Cc,U.N,0];Q[75]=[U.bd,U.N,0];Q[107]=[U.cd,U.N,0];Q[155]=[U.Od,U.T,2];var Qb=[10,254,20,2,40,4,80,6,160,8,60,10,14,12,26,14,12,16,24,18,48,20,96,22,192,24,72,26,16,28,32,30];var Rb=[[0,1,0,0,0,0,0,0],[0,1,1,0,0,0,0,0],[0,1,1,1,1,0,0,0],[1,0,0,1,1,1,1,1]];function Sb(a){A('Initializing pulse channel #'+a);this.id=a;this.l=!1;this.gain=1;this.f=this.c=this.O=0;this.la=this.m=!1;this.s=0;this.L=!1;this.g=this.h=0;this.$=!1;this.v=0;this.na=!1;this.i=0;this.ua=this.P=!1;this.ma=this.j=this.S=this.R=0}c=Sb.prototype;c.reset=function(){A('Resetting pulse channel #'+this.id);this.f=this.i=this.g=this.h=this.c=this.O=0;this.l=!1;Ba(this,0);Ca(this,0);this.qa(0);this.pa(0)};
function Ba(a,b){a.ma=(b&192)>>>6;a.m=0!==(b&32);a.la=0!==(b&16);a.s=b&15;a.$=a.m;a.v=a.s}function Ca(a,b){a.na=0!==(b&128);a.R=(b&112)>>>4;a.ua=0!==(b&8);a.S=b&7;a.P=!0}c.qa=function(a){this.c=this.c&1792|a&255};c.pa=function(a){this.l&&(this.f=Qb[(a&248)>>>3]);this.c=this.c&255|(a&7)<<8;this.j=0;this.L=!0};c.w=function(){0>=--this.O&&(this.O=this.c+1<<1,this.j=this.j+1&7)};function Tb(a){a.L?(a.L=!1,a.h=a.v,a.g=15):0<a.h?a.h--:(a.h=a.v,0<a.g?a.g--:a.$&&(a.g=15))}
function Ub(a){0<a.i?a.i--:(a.na&&a.S&&8<=a.c&&2048>a.c+Vb(a)&&(a.c+=Vb(a)),a.i=a.R);a.P&&(a.P=!1,a.i=a.R)}function Vb(a){var b=a.c>>>a.S;return a.ua?1===a.id?~b:-b:b}c.Z=function(){return this.f&&8<=this.c&&2048>this.c+Vb(this)?this.gain*(this.la?this.s:this.g)*Rb[this.ma][this.j]:0};var Wb=[15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15];function Xb(){A('Initializing triangle channel');this.i=!1;this.gain=1;this.c=this.f=this.l=0;this.j=!1;this.v=this.g=0;this.m=this.s=!1;this.h=15}c=Xb.prototype;c.reset=function(){A('Resetting triangle channel');this.c=this.g=this.h=this.f=this.l=0;this.i=!1;Da(this,0);this.qa(0);this.pa(0)};function Da(a,b){a.j=0!==(b&128);a.v=b&127;a.s=a.j}c.qa=function(a){this.f=this.f&1792|a&255};
c.pa=function(a){this.i&&(this.c=Qb[(a&248)>>>3]);this.f=this.f&255|(a&7)<<8;this.m=!0};c.w=function(){0>=--this.l&&(this.l=this.f+1,this.c&&this.g&&3<this.f&&(this.h=this.h+1&31))};c.Z=function(){return this.gain*Wb[this.h]};function Yb(){A('Initializing noise channel');this.j=!1;this.gain=1;this.S=!1;this.O=this.v=0;this.R=null;this.c=0;this.P=this.s=!1;this.i=0;this.m=!1;this.f=this.h=0;this.L=!1;this.g=this.l=0}c=Yb.prototype;c.reset=function(){A('Resetting noise channel');this.f=this.h=this.v=0;this.g=1;this.c=0;this.j=!1;Ea(this,0);this.qa(0);this.pa(0)};c.Ra=function(a){this.R=a.Tc};function Ea(a,b){a.s=0!==(b&32);a.P=0!==(b&16);a.i=b&15;a.L=a.s;a.l=a.i}c.qa=function(a){this.S=0!==(a&128);this.O=this.R[a&15]};
c.pa=function(a){this.j&&(this.c=Qb[(a&248)>>>3]);this.m=!0};c.w=function(){0>=--this.v&&(this.v=this.O,this.g=this.g>>>1|(this.g&1^this.g>>>(this.S?6:1)&1)<<14)};c.Z=function(){return!this.c||this.g&1?0:this.gain*(this.P?this.i:this.f)};function Zb(){A('Initializing DMC channel');this.c=0;this.gain=1;this.R=this.L=0;this.P=null;this.f=this.i=this.s=this.m=0;this.S=!1;this.g=this.j=-1;this.h=this.O=0;this.l=this.v=!1;this.A=this.K=null}c=Zb.prototype;c.connect=function(a){A('Connecting DMC channel');this.K=a.K;this.A=a.A};c.reset=function(){A('Resetting DMC channel');this.L=0;this.g=this.j=-1;this.h=this.O=0;Ga(this,!1);Fa(this,0);this.c=0;this.m=49152;this.s=1};
function Ga(a,b){b?0===a.f&&(a.i=a.m,a.f=a.s):a.f=0;a.l=!1;eb(a.K,8)}c.Ra=function(a){this.P=a.Hc};function Fa(a,b){a.v=0!==(b&128);a.S=0!==(b&64);a.R=a.P[b&15];a.v||(a.l=!1,eb(a.K,8))}
c.w=function(){0<this.h&&this.h--;if(0>=--this.L){this.L=this.R;if(0>this.j&&0<this.f&&(this.j=this.A.read(this.i),this.h=4,65535>this.i?this.i++:this.i=32768,0>=--this.f))if(this.S)this.i=this.m,this.f=this.s;else if(this.v){this.l=!0;var a=this.K;a.g|=8}0>=--this.O&&(this.O=8,this.g=this.j,this.j=-1);0<=this.g&&(this.g&1?125>=this.c&&(this.c+=2):2<=this.c&&(this.c-=2),this.g>>>=1)}};c.Z=function(){return this.gain*this.c};function $b(){A('Initializing APU');this.ea=new Sb(1);this.fa=new Sb(2);this.ha=new Xb;this.da=new Yb;this.Y=new Zb;this.s=[this.ea,this.fa,this.ha,this.da,this.Y];this.c=-1;this.lb=this.kb=null;this.Ic=this.i=0;this.g=!1;this.f=0;this.l=this.j=!1;this.v=this.m=this.sampleRate=0;this.K=this.h=null}c=$b.prototype;c.connect=function(a){A('Connecting APU');this.K=a.K;this.Y.connect(a)};
c.reset=function(){A('Resetting APU');this.ea.reset();this.fa.reset();this.ha.reset();this.da.reset();this.Y.reset();ac(this);Ha(this,0)};c.Ra=function(a){A('Setting APU region parameters');this.kb=a.kb;this.lb=a.lb;this.v=29829.55*a.pc;this.da.Ra(a);this.Y.Ra(a)};c.qb=function(a){this.sampleRate=a};function bc(a,b){A((b?'Setting':'Removing')+' APU callback');a.h=b}c.sb=function(a,b){A('Setting volume of APU channel #'+a+' to '+b);this.s[a].gain=b};c.Wa=function(a){return this.s[a].gain};
function Ha(a,b){a.Ic=b;a.g=0!==(b&128);a.l=0!==(b&64);a.i=4;a.f=0;0>a.c&&(a.c=cc(a));a.l&&ac(a);a.g&&(dc(a),ec(a))}function cc(a){return(a.g?a.lb:a.kb)[a.f]}function ac(a){a.j=!1;eb(a.K,4)}c.uc=function(){var a=0<this.ea.f|(0<this.fa.f)<<1|(0<this.ha.c)<<2|(0<this.da.c)<<3|(0<this.Y.f)<<4|this.j<<6|this.Y.l<<7;ac(this);return a};c.Mb=function(){return 0<this.Y.h};
c.w=function(){this.i&&0>=--this.i&&(this.c=cc(this));if(0>=--this.c)switch(this.f=(this.f+1)%6,this.c=cc(this),this.f){case 1:ec(this);break;case 2:ec(this);dc(this);break;case 3:ec(this);break;case 4:fc(this);break;case 5:ec(this);dc(this);fc(this);break;case 0:fc(this)}this.ea.w();this.fa.w();this.ha.w();this.da.w();this.Y.w();this.h&&0>=--this.m&&(this.m+=this.v/this.sampleRate,this.h(this.Z()))};
function ec(a){Tb(a.ea);Tb(a.fa);var b=a.ha;b.m?b.g=b.v:0<b.g&&b.g--;b.s||(b.m=!1);a=a.da;a.m?(a.m=!1,a.h=a.l,a.f=15):0<a.h?a.h--:(a.h=a.l,0<a.f?a.f--:a.L&&(a.f=15))}function dc(a){var b=a.ea;0<b.f&&!b.m&&b.f--;Ub(b);b=a.fa;0<b.f&&!b.m&&b.f--;Ub(b);b=a.ha;0<b.c&&!b.j&&b.c--;a=a.da;0<a.c&&!a.s&&a.c--}function fc(a){a.l||a.g||(a.j=!0,a=a.K,a.g|=4)}
c.Z=function(){var a=0,b=this.ea.Z(),d=this.fa.Z();if(b||d)a+=95.88/(8128/(b+d)+100);b=this.ha.Z();d=this.da.Z();var e=this.Y.Z();if(b||d||e)a+=159.79/(1/(b/8227+d/12241+e/22638)+100);return a};function gc(){var a=void 0===a?{}:a;A('Initializing NES');this.K=a.K||new vb;this.u=a.u||new ub;this.o=a.o||new $b;this.ca=a.ca||new Pa;this.A=a.A||new va;this.C=a.C||new Ka;this.region=this.M=this.ja=null;this.K.connect(this);this.u.connect(this);this.o.connect(this);this.ca.connect(this);this.A.connect(this);hc(this)}c=gc.prototype;c.Tb=function(a){this.region=a;hc(this)};function ic(a){return a.region||a.ja&&a.ja.region||'NTSC'}
function hc(a){A('Updating region parameters');var b=ic(a),d=qa(b);A('Detected region: "'+b+'"');a.u.Ra(d);a.o.Ra(d)}function jc(a,b){a.ja&&(A('Removing current cartridge'),a.M&&(a.M.disconnect(),a.M=null),a.ja=null);if(b){A('Inserting cartridge');a.ja=b;var d=b.M,e=ib[d];if(e)A('Creating "'+d+'" mapper'),b=new e(b);else throw Error('Invalid mapper: '+n(d));a.M=b;a.M.connect(a);hc(a);a.Ob()}}
c.Ob=function(){this.ja&&(this.A.reset(),this.C.reset(),this.M.reset(),this.u.reset(),this.o.reset(),this.ca.reset(),this.K.reset())};c.reset=function(){var a=this.K;a.g|=1};c.xc=function(a,b){var d=this.A.Lb(a);d&&d.disconnect();this.A.xc(a,b);b&&b.connect(this)};c.Lb=function(a){return this.A.Lb(a)};
c.Sb=function(a){var b=this.u;A('Setting PPU base palette');b.Lc=a;for(a=0;a<b.zb.length;a++){var d=b.zb,e=a,h=b.Lc,l=a&6?.75:1,m=a&5?.75:1,p=a&3?.75:1;A('Creating palette variant ('+l+', '+m+', '+p+')');for(var r=new Uint32Array(64),q=0;64>q;q++){var F=f(pb(h[q])),K=F.next().value,G=F.next().value;F=F.next().value;K=Math.floor(l*K);G=Math.floor(m*G);F=Math.floor(p*F);r[q]=mb(K,G,F)}d[e]=r}b.ua=b.zb[b.Wb]};
c.pb=function(a){if(this.ja){var b=this.u;b.j=a;b.O=0;for(b.Kb=!1;!this.u.Kb;)this.K.step()}else for(b=0;b<a.length;b++){var d=~~(255*Math.random());a[b]=mb(d,d,d)}};c.vc=function(a){if(this.ja){var b=this.u;b.j=a;b.O=0;b.Kb=!1;this.u.vc()}else a.fill(qb)};c.qc=function(){return this.M?this.M.qc():null};function kc(){this.gb=new Uint8Array(24);this.gb[19]=1;this.c=0}kc.prototype.connect=function(){A('Connecting joypad')};kc.prototype.disconnect=function(){A('Disconnecting joypad')};kc.prototype.zc=function(){this.c=0};kc.prototype.read=function(){var a=this.gb[this.c];this.c=(this.c+1)%this.gb.length;return a};function lc(){this.Ac=!1;this.f=this.c=-1;this.u=null}lc.prototype.connect=function(a){A('Connecting zapper');this.u=a.u};lc.prototype.disconnect=function(){A('Disconnecting zapper');this.u=null};lc.prototype.zc=function(){};lc.prototype.read=function(){var a=this.Ac<<4,b;if(b=0<=this.c&&256>this.c&&0<=this.f&&240>this.f){b=this.u;var d=this.f;if(d<b.h-5||d>=b.h)b=!1;else{var e=f(pb(b.j[256*d+this.c]));b=e.next().value;d=e.next().value;e=e.next().value;b=18<b||18<d||18<e}}return a|!b<<3};var mc={0:'NROM',1:'MMC1',2:'UNROM',3:'CNROM',4:'MMC3',7:'AOROM',11:'COLOR_DREAMS',34:'BNROM'},nc={},oc=(nc[17]='SUROM',nc[18]='SOROM',nc[19]='SXROM',nc);function pc(a){return 78===a[0]&&69===a[1]&&83===a[2]&&26===a[3]}function qc(a){return 0<a?128*Math.pow(2,a-1):0}
var rc={name:'iNES / NES 2.0',parse:function(a){if(!pc(a))throw Error('Incorrect signature');if(16>a.length)throw Error('Input is too short: expected at least 16 B but got '+k(a.length));var b=a[4],d=a[5],e=a[7]&240|a[6]>>>4;var h=a[6]&8?'4S':a[6]&1?'V':'H';if(8===(a[7]&12)){A('Detected NES 2.0 format');var l=2;e|=(a[8]&15)<<8;var m=(a[8]&240)>>>4;b|=(a[9]&15)<<8;d|=(a[9]&240)<<4;var p=qc((a[10]&240)>>>4);var r=qc((a[11]&240)>>>4);var q=p+qc(a[10]&15);var F=r+qc(a[11]&15);var K=a[12]&1?'PAL':'NTSC'}else A('Detected iNES format'),
l=1,q=8192*(a[8]||1),p=a[6]&2?q:0,F=d?0:8192,r=0,K=a[9]&1?'PAL':'NTSC';if(0===b)throw Error('Invalid header: 0 PRG ROM units');var G=16+(a[6]&4?512:0);b*=16384;var O=G+b;d*=8192;var I=O+d,L=mc[e]||e.toString();'BNROM'===L&&0<d&&(L='NINA_001');e=oc[e<<4|m];if(a.length<I)throw Error('Input is too short: expected at least '+k(I)+' but got '+k(a.length));return{version:l,nb:h,region:K,M:L,le:e,xa:b,Qa:a.subarray(G,O),ob:q,Qb:p,Ua:d,ib:d?a.subarray(O,I):void 0,hb:F,Jb:r}}};rc.supports=pc;var sc=[rc];var W='0123456789abcdef'.split(''),tc=[-2147483648,8388608,32768,128],uc=[24,16,8,0];var vc,wc=window.AudioContext||window.webkitAudioContext;function xc(a,b){var d=this;A('Initializing audio processor');this.c=a;this.i=b.createScriptProcessor(4096,0,1);this.i.onaudioprocess=function(e){e=e.outputBuffer;d.g||(d.h.fill(d.l,d.f),yc(d));e.copyToChannel?e.copyToChannel(d.outputBuffer,0):e.getChannelData(0).set(d.outputBuffer);d.g=!1;d.c.o.qb(d.c.o.sampleRate+100*(.5-d.f/4096))};this.l=0;this.j=this.j.bind(this);this.f=0;this.h=new Float32Array(4096);this.outputBuffer=new Float32Array(4096);this.g=!1}
xc.prototype.connect=function(a){A('Connecting audio processor');bc(this.c.o,this.j);this.i.connect(a)};xc.prototype.disconnect=function(){A('Disconnecting audio processor');bc(this.c.o,null);this.i.disconnect()};xc.prototype.qb=function(a){A('Setting sample rate to '+a+' Hz');this.c.o.qb(a)};xc.prototype.j=function(a){if(4096===this.f){if(this.g)return;yc(this)}this.l=this.h[this.f++]=a};function yc(a){var b=f([a.h,a.outputBuffer]);a.outputBuffer=b.next().value;a.h=b.next().value;a.g=!0;a.f=0};var zc={master:-1,pulse1:0,pulse2:1,triangle:2,noise:3,dmc:4};function Ac(a,b){A('Initializing audio mixer');this.f=a;this.volume=.5;this.c=b.createGain();this.c.connect(b.destination);this.c.gain.value=this.volume}Ac.prototype.Va=function(){return this.c};Ac.prototype.sb=function(a,b){if('number'!==typeof b||0>b||1<b)throw Error('Invalid audio volume: '+n(b));this.Wa(a)!==b&&(A('Setting volume of "'+a+'" channel to '+~~(100*b)+'%'),a=zc[a],0<=a?this.f.o.sb(a,b):(this.volume=b,this.c.gain.value=this.volume))};
Ac.prototype.Wa=function(a){var b=zc[a];if(null==b)throw Error('Invalid audio channel: '+n(a));return 0<=b?this.f.o.Wa(b):this.volume};function Bc(a){A('Initializing audio');this.f=!0;this.active=!1;this.speed=1;null==vc&&(vc=new wc);this.c=vc;this.g=new xc(a,this.c);this.h=new Ac(a,this.c);Cc(this);this.g.qb(this.c.sampleRate/this.speed)}c=Bc.prototype;c.fd=function(a){if('boolean'!==typeof a)throw Error('Invalid audio enabled: '+n(a));this.f!==a&&(A('Audio '+(a?'enabled':'disabled')),this.f=a,Cc(this))};c.ed=function(){return this.f};
c.setActive=function(a){this.active!==a&&(A('Audio '+(a?'resumed':'suspended')),this.active=a,Cc(this))};function Cc(a){a.f&&a.active?(a.g.connect(a.h.Va()),a.c.resume()):a.g.disconnect()}c.rb=function(a){this.speed!==a&&(A('Setting audio speed to '+a+'x'),this.speed=a,this.g.qb(this.c.sampleRate/this.speed))};c.sb=function(a,b){this.h.sb(a,b)};c.Wa=function(a){return this.h.Wa(a)};var Dc=[1,2];function X(a,b){this.source=a;this.name=b}X.prototype.Ma=function(a){return this.source===a.source&&this.name===a.name};X.prototype.toString=function(){return this.source+'.'+this.name};var Ec={65:'a',66:'b',67:'c',68:'d',69:'e',70:'f',71:'g',72:'h',73:'i',74:'j',75:'k',76:'l',77:'m',78:'n',79:'o',80:'p',81:'q',82:'r',83:'s',84:'t',85:'u',86:'v',87:'w',88:'x',89:'y',90:'z',48:'0',49:'1',50:'2',51:'3',52:'4',53:'5',54:'6',55:'7',56:'8',57:'9',32:'space',188:',',190:'.',191:'/',186:';',222:"'",220:'\\',219:'[',221:']',192:'`',189:'-',187:'=',112:'f1',113:'f2',114:'f3',115:'f4',116:'f5',117:'f6',118:'f7',119:'f8',120:'f9',121:'f10',122:'f11',123:'f12',16:'shift',17:'ctrl',18:'alt',
37:'left',38:'up',39:'right',40:'down',9:'tab',36:'home',35:'end',33:'page-up',34:'page-down',27:'escape',19:'pause',13:'enter',8:'backspace',45:'insert',46:'delete',20:'caps-lock',144:'num-lock',145:'scroll-lock',96:'numpad-0',97:'numpad-1',98:'numpad-2',99:'numpad-3',100:'numpad-4',101:'numpad-5',102:'numpad-6',103:'numpad-7',104:'numpad-8',105:'numpad-9',107:'add',109:'subtract',106:'multiply',111:'divide',110:'decimal-point'};
function Fc(a){var b=this;A('Initializing keyboard');this.g=a;this.c=function(d){return Gc(b,d,!0)};this.f=function(d){return Gc(b,d,!1)}}Fc.prototype.fc=function(){A('Activating keyboard');window.addEventListener('keydown',this.c);window.addEventListener('keyup',this.f)};Fc.prototype.mc=function(){A('Deactivating keyboard');window.removeEventListener('keydown',this.c);window.removeEventListener('keyup',this.f)};
function Gc(a,b,d){a.g.ga(new X('keyboard',Ec[b.keyCode||b.which]),d)&&b.preventDefault()};var Hc={0:'left',1:'middle',2:'right'};function Ic(a){var b=this;A('Initializing mouse');this.c=a;this.f=function(d){b.c.ga(new X('mouse',Hc[d.button]),!0)&&d.preventDefault()};this.h=function(d){b.c.ga(new X('mouse',Hc[d.button]),!1)&&d.preventDefault()};this.g=function(d){b.c.ga(new X('mouse','cursor'),[d.clientX,d.clientY])}}
Ic.prototype.fc=function(){A('Activating mouse');window.addEventListener('mousedown',this.f);window.addEventListener('mouseup',this.h);window.addEventListener('mousemove',this.g)};Ic.prototype.mc=function(){A('Deactivating mouse');window.removeEventListener('mousedown',this.f);window.removeEventListener('mouseup',this.h);window.removeEventListener('mousemove',this.g)};var Jc=['left-stick-x','left-stick-y','right-stick-x','right-stick-y'],Kc='a b x y left-bumper right-bumper left-trigger right-trigger back start left-stick right-stick dpad-up dpad-down dpad-left dpad-right guide'.split(' ');function Lc(a){A('Initializing gamepads');this.g=a;this.c=null;this.f=0}Lc.prototype.fc=function(){navigator.getGamepads?(A('Activating gamepads'),Mc(this)):ua('Cannot activate gamepads (Gamepad API is not available)')};Lc.prototype.mc=function(){A('Deactivating gamepads');cancelAnimationFrame(this.f)};
function Mc(a){a.f=requestAnimationFrame(function(){var b=Nc();if(a.c)for(var d=a.c,e=0;e<d.length;e++){var h=d[e],l=b[e];if(h&&l){for(var m=h.axes,p=l.axes,r=0;r<Math.min(m.length,p.length);r++)if(m[r]!==p[r]){var q=a,F=r,K=m[r],G=p[r];K&&q.ga(l,Oc(l,F,K),!1);G&&q.ga(l,Oc(l,F,G),!0)}h=h.buttons;m=l.buttons;for(p=0;p<Math.min(h.length,m.length);p++)h[p]!==m[p]&&a.ga(l,'standard'===l.mapping?Kc[p]:'button-'+p,m[p])}}a.c=b;Mc(a)})}
function Nc(){return Array.from(navigator.getGamepads()).map(function(a){return a&&{index:a.index,mapping:a.mapping,axes:a.axes.map(Math.round),buttons:a.buttons.map(function(b){return b.pressed})}})}Lc.prototype.ga=function(a,b,d){this.g.ga(new X('gamepad'+a.index,b),d)};function Oc(a,b,d){d=0<d?'+':'-';return'standard'===a.mapping?Jc[b]+d:'axis-'+b+d};var Pc={},Qc=(Pc.keyboard={cc:Fc,rc:!1},Pc.mouse={cc:Ic,rc:!1},Pc.gamepad={cc:Lc,rc:!0},Pc);function Rc(a){A('Initializing sources');this.h=a;this.f=[];this.g=this.active=!1;this.c=null;for(var b in Qc)this.f.push(new Qc[b].cc(this))}Rc.prototype.setActive=function(a){this.active!==a&&(A('Sources '+(a?'activated':'deactivated')),a?this.f.forEach(function(b){return b.fc()}):this.f.forEach(function(b){return b.mc()}),this.active=a)};
Rc.prototype.i=function(a){if('function'!==typeof a)throw Error('Invalid record input callback: '+n(a));A('Recording source input');this.c=a;this.g=this.active;this.setActive(!0)};Rc.prototype.ga=function(a,b){return this.c?(b||(A('Caught "'+a+'" source input'),this.setActive(this.g),this.c(a.toString()),this.c=null),!0):this.h.ga(a,b)};function Sc(a,b,d){this.port=a;this.La=b;this.name=d}Sc.prototype.Ma=function(a){return this.port===a.port&&this.La===a.La&&this.name===a.name};Sc.prototype.toString=function(){return this.port+'.'+this.La+'.'+this.name};var Tc={a:0,b:1,select:2,start:3,up:4,down:5,left:6,right:7};function Uc(a){this.c=a}Uc.prototype.Kc=function(){return this.c};Uc.prototype.Ya=function(a,b){if(a in Tc){if('boolean'!==typeof b)throw Error('Invalid joypad button state: '+n(b));this.c.gb[Tc[a]]=b?1:0}else throw Error('Invalid joypad button: '+n(a));};Uc.prototype.Va=function(a){if(a in Tc)return 1===this.c.gb[Tc[a]];throw Error('Invalid joypad button: '+n(a));};function Vc(a){this.c=a}Vc.prototype.Kc=function(){return this.c};
Vc.prototype.Ya=function(a,b){if('trigger'===a){if('boolean'!==typeof b)throw Error('Invalid zapper trigger state: '+n(b));this.c.Ac=b}else if('beam'===a){if(!Array.isArray(b)||2!==b.length)throw Error('Invalid zapper beam position: '+n(b));b=f(b);a=b.next().value;b=b.next().value;if('number'!==typeof a)throw Error('Invalid zapper beam X position: '+n(a));if('number'!==typeof b)throw Error('Invalid zapper beam Y position: '+n(b));var d=this.c;d.c=a;d.f=b}else throw Error('Invalid zapper input: '+
n(a));};Vc.prototype.Va=function(a){if('trigger'===a)return this.c.Ac;if('beam'===a)return a=this.c,[a.c,a.f];throw Error('Invalid zapper input: '+n(a));};var Wc={},Xc=(Wc.joypad={Zb:kc,Dc:Uc},Wc.zapper={Zb:lc,Dc:Vc},Wc);function Yc(a,b){if('string'===typeof a){if(null==b||b===X){var d=a.split('.');if(2!==d.length)d=null;else{var e=f(d);d=e.next().value;e=e.next().value;d=new X(d,e)}if(d){a=d.source;b=a.replace(/[0-9]+$/,'');e=Qc[b];if(!e||e.rc!==(a!==b))throw Error('Invalid input source: '+n(a));return d}}if(null==b||b===Sc){d=a.split('.');if(3!==d.length)d=null;else{var h=f(d);d=h.next().value;e=h.next().value;h=h.next().value;var l=parseInt(d,10);d=new Sc(isNaN(l)?d:l,e,h)}if(d){a=d.port;b=d.La;if(!(0<=Dc.indexOf(a)))throw Error('Invalid input port: '+
n(a));if(!(b in Xc))throw Error('Invalid input device: '+n(b));return d}}}if(null!=b)throw Error('Invalid '+(b===X?'source':'device')+' input: '+n(a));throw Error('Invalid input: '+n(a));};function Zc(a){A('Initializing devices');this.c=a;a={};for(var b=f(Dc),d=b.next();!d.done;d=b.next()){d=d.value;a[d]={};for(var e in Xc){var h=Xc[e];a[d][e]=new h.Dc(new h.Zb)}}this.fb=a;this.set(1,'joypad');this.set(2,'zapper')}Zc.prototype.set=function(a,b){if(!(0<=Dc.indexOf(a)))throw Error('Invalid port: '+n(a));if(null!==b&&!(b in Xc))throw Error('Invalid device: '+n(b));this.get(a)!==b&&(A('Setting device on port '+a+' to "'+(b||'none')+'"'),this.c.xc(a,null!==b?this.fb[a][b].Kc():null))};
Zc.prototype.get=function(a){if(!(0<=Dc.indexOf(a)))throw Error('Invalid port: '+n(a));a=this.c.Lb(a);for(var b in Xc)if(a instanceof Xc[b].Zb)return b;return null};Zc.prototype.Ya=function(a,b){a=Yc(a,Sc);this.fb[a.port][a.La].Ya(a.name,b)};Zc.prototype.Va=function(a){a=Yc(a,Sc);return this.fb[a.port][a.La].Va(a.name)};function $c(){A('Initializing input map');this.c=[]}function ad(a,b){if(!b||'object'!==typeof b)throw Error('Invalid mapping: '+n(b));A('Unmapping all inputs');a.c.length=0;for(var d in b){var e=b[d];if('string'===typeof e)a.set(d,e);else if(Array.isArray(e)){e=f(e);for(var h=e.next();!h.done;h=e.next())a.set(d,h.value)}else throw Error('Invalid source input(s): '+n(e));}}c=$c.prototype;
c.set=function(a,b){a=Yc(a,Sc);b=Yc(b,X);this.has(a,b)||(A('Mapping "'+a+'" input to "'+b+'"'),this.c.push({jb:a,tb:b}))};c.get=function(a){var b=[];a=Yc(a);this.forEach(a,function(d){b.push(d.toString())});return b};c.yd=function(a){var b=Yc(a);A('Unmapping "'+b+'" input');this.c=this.c.filter(function(d){var e=d.tb;return!d.jb.Ma(b)&&!e.Ma(b)})};c.has=function(a,b){for(var d=f(this.c),e=d.next();!e.done;e=d.next())if(e=e.value,e.jb.Ma(a)&&e.tb.Ma(b))return!0;return!1};
c.forEach=function(a,b){if(a instanceof Sc)for(var d=f(this.c),e=d.next();!e.done;e=d.next())e=e.value,e.jb.Ma(a)&&b(e.tb);else if(a instanceof X)for(d=f(this.c),e=d.next();!e.done;e=d.next())e=e.value,e.tb.Ma(a)&&b(e.jb)};function bd(a,b,d){A('Initializing input router');this.map=a;this.f=b;this.video=d;this.c=null}
bd.prototype.ga=function(a,b){var d=this;if('mouse'===a.source){if(null==this.video.Z())return!1;if('cursor'===a.name){this.c=b;b=cd(this.video,b[0],b[1]);a=f(Dc);for(var e=a.next();!e.done;e=a.next())this.f.fb[e.value].zapper.Ya('beam',b);return!0}if(this.c){var h=f(this.c);e=h.next().value;h=h.next().value;var l=dd(this.video),m=l.top,p=l.bottom,r=l.right;if(e<l.left||e>r||h<m||h>p)return!1}}var q=!1;this.map.forEach(a,function(F){d.f.fb[F.port][F.La].Ya(F.name,b);q=!0});return q};function ed(){this.index=this.time=0;this.c=Array(50).fill(0)}function fd(a){var b=void 0===b?window.performance.now():b;a.c[a.index]=b-a.time;a.index=(a.index+1)%a.c.length;a.time=b}ed.prototype.get=function(){return 1E3/(this.c.reduce(function(a,b){return a+b})/this.c.length)};var gd={},hd=(gd.auto=null,gd.ntsc='NTSC',gd.pal='PAL',gd),id={setActive:function(){},rb:function(){}};
function jd(a,b,d,e){var h=this;A('Initializing system');this.c=a;this.video=b;this.audio=d||id;this.j=!1;this.f='auto';this.speed=1;this.h=this.g=0;this.i=e;this.l=new ed;this.c.Tb(hd[this.f]);this.audio.rb(this.speed);'https:'===location.protocol&&document.addEventListener('visibilitychange',function(){document.hidden?(A('Lost visibility'),h.j=h.Na(),h.eb()):(A('Gained visibility'),h.j&&h.start())})}c=jd.prototype;
c.start=function(){var a=this;if(!this.Na()){A('Starting execution');var b=1E3/(this.speed*qa(ic(this.c)).pc);this.g=setInterval(function(){return a.step()},b);this.audio.setActive(!0);this.i.setActive(!0)}};c.eb=function(){this.Na()&&(A('Stopping execution'),clearInterval(this.g),cancelAnimationFrame(this.h),this.g=0,this.audio.setActive(!1),this.i.setActive(!1))};c.Na=function(){return!!this.g};
c.step=function(){var a=this;this.video.Z()&&(this.video.pb(),cancelAnimationFrame(this.h),this.h=requestAnimationFrame(function(){return a.video.aa()}));fd(this.l)};c.Ob=function(){A('HW reset');this.c.Ob()};c.reset=function(){A('SW reset');this.c.reset()};c.Tb=function(a){if(!(a in hd))throw Error('Invalid region: '+n(a));this.f!==a&&(A('Setting region to "'+a+'"'),this.f=a,this.c.Tb(hd[this.f]),this.Na()&&(this.eb(),this.start()))};c.Md=function(){return this.f};
c.rb=function(a){if('number'!==typeof a||0>=a)throw Error('Invalid speed: '+n(a));this.speed!==a&&(A('Setting emulation speed to '+a+'x'),this.speed=a,this.audio.rb(this.speed),this.Na()&&(this.eb(),this.start()))};c.Nd=function(){return this.speed};c.be=function(){return this.l.get()};var kd=['maximized','normalized','stretched'],ld={position:'fixed',top:'0',right:'0',bottom:'0',left:'0',margin:'auto',width:'auto',height:'auto'};var md;function nd(){if(null==md){A('Creating auxiliary canvas');var a=document.createElement('canvas');a.width=256;a.height=240;md=od(a)}return md}function od(a){A('Getting 2d canvas context');a=a.getContext('2d',{alpha:!1});if(null==a)throw Error('Unable to get 2d canvas context');return a}function pd(a){this.c=od(a);this.g='nearest';this.f=1}c=pd.prototype;c.kc=function(a,b,d,e){d=this.c.createImageData(d,e);e=(new Uint32Array(d.data.buffer)).fill(qb);return{x:a,y:b,data:e,image:d}};
c.aa=function(a){(1!==this.f?nd():this.c).putImageData(a.image,a.x,a.y)};c.Gc=function(){};c.end=function(){if(1!==this.f){var a='linear'===this.g;this.c.imageSmoothingEnabled=a;this.c.mozImageSmoothingEnabled=a;this.c.oImageSmoothingEnabled=a;this.c.msImageSmoothingEnabled=a;a=nd().canvas;var b=this.c.canvas;this.c.drawImage(a,0,0,a.width,a.height,0,0,b.width,b.height)}};c.Rb=function(a){this.g=a};c.Ub=function(a){this.f=a};function qd(a,b,d){b=a.createShader(b);a.shaderSource(b,d);a.compileShader(b);if(!a.getShaderParameter(b,a.COMPILE_STATUS))throw Error('Shader compilation error: '+a.getShaderInfoLog(b));return b}
function rd(a){a:{for(var b={alpha:!1,depth:!1,antialias:!1},d=f(['webgl','experimental-webgl']),e=d.next();!e.done;e=d.next())if(e=e.value,A('Getting '+e+' canvas context'),e=a.getContext(e,b))break a;throw Error('Unable to get webgl or experimental-webgl canvas context');}a=e;b=a.createProgram();a.attachShader(b,qd(a,a.VERTEX_SHADER,'\n  uniform vec2 uScreenSize;\n  attribute vec2 aVertexPosition;\n  attribute vec2 aTextureCoord;\n  varying vec2 vTextureCoord;\n\n  void main(void) {\n    float x = aVertexPosition.x / (0.5 * uScreenSize.x) - 1.0; // [0, width] -> [-1, 1]\n    float y = 1.0 - aVertexPosition.y / (0.5 * uScreenSize.y); // [height, 0] -> [-1, 1]\n    gl_Position = vec4(x, y, 0.0, 1.0);\n    vTextureCoord = aTextureCoord;\n  }\n'));
a.attachShader(b,qd(a,a.FRAGMENT_SHADER,'\n  precision mediump float;\n\n  uniform sampler2D uSampler;\n  varying vec2 vTextureCoord;\n\n  void main(void) {\n    gl_FragColor = texture2D(uSampler, vTextureCoord);\n  }\n'));a.linkProgram(b);if(!a.getProgramParameter(b,a.LINK_STATUS))throw Error('Shader linking error');d=a.getUniformLocation(b,'uScreenSize');e=a.getUniformLocation(b,'uSampler');var h=a.getAttribLocation(b,'aVertexPosition'),l=a.getAttribLocation(b,'aTextureCoord');a.enableVertexAttribArray(h);
a.enableVertexAttribArray(l);a.useProgram(b);this.c=a;this.f=1;this.g='nearest';this.i=d;this.h=e;this.l=h;this.j=l}c=rd.prototype;
c.kc=function(a,b,d,e){d=sd(d);e=sd(e);var h=this.c,l=(new Uint32Array(d*e)).fill(qb),m=this.c;b=new Float32Array([a,b,a+d,b,a+d,b+e,a,b+e]);a=m.createBuffer();m.bindBuffer(m.ARRAY_BUFFER,a);m.bufferData(m.ARRAY_BUFFER,b,m.STATIC_DRAW);m=this.c;b=new Float32Array([0,0,1,0,1,1,0,1]);var p=m.createBuffer();m.bindBuffer(m.ARRAY_BUFFER,p);m.bufferData(m.ARRAY_BUFFER,b,m.STATIC_DRAW);return{width:d,height:e,data:l,$c:a,coords:p,me:h.createTexture()}};
c.aa=function(a){var b=this.c,d='linear'===this.g?b.LINEAR:b.NEAREST,e=new Uint8Array(a.data.buffer);b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,a.me);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,d);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,d);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,a.width,a.height,0,b.RGBA,b.UNSIGNED_BYTE,e);b=this.c;b.uniform1i(this.h,0);b.bindBuffer(b.ARRAY_BUFFER,a.$c);b.vertexAttribPointer(this.l,2,b.FLOAT,!1,0,0);b.bindBuffer(b.ARRAY_BUFFER,a.coords);b.vertexAttribPointer(this.j,
2,b.FLOAT,!1,0,0);b=this.c;b.bindBuffer(b.ARRAY_BUFFER,a.$c);b.drawArrays(b.TRIANGLE_FAN,0,4)};c.Gc=function(){var a=this.c,b=a.canvas,d=b.width;b=b.height;var e=d/this.f,h=b/this.f;a.viewport(0,0,d,b);a.clearColor(0,0,0,1);a.clear(a.COLOR_BUFFER_BIT);a.uniform2f(this.i,e,h)};c.end=function(){this.c.flush()};c.Ub=function(a){this.f=a};c.Rb=function(a){this.g=a};function sd(a){for(var b=1;b<a;)b*=2;return b};var td={},ud=(td.canvas=pd,td.webgl=rd,td),vd={},wd=(vd.webgl='canvas',vd);for(var xd=null,yd=f(['','webkit','moz','ms']),zd=yd.next();!zd.done;zd=yd.next()){var Ad=zd.value;if(Bd('fullscreenElement',Ad)in document){xd=Ad;break}}function Bd(a,b){b=void 0===b?xd:b;'moz'===b&&(a=a.replace('exit','cancel').replace('screen','Screen'));return b+(a.charAt(0).toUpperCase()+a.slice(1))}
function Cd(){var a=this;this.c=null;Dd('change',function(){var b=a.is()?'enter':'exit';A('Fullscreen '+b+'ed');a.c&&a.c.type===b&&(a.c.resolve(),a.c=null)});Dd('error',function(){y.error('Detected fullscreen error');a.c&&(a.c.reject(Error('Failed to '+a.c.type+' fullscreen')),a.c=null)})}Cd.prototype.is=function(){return null!=xd?null!=document[Bd('fullscreenElement')]:!1};
function Dd(a,b){null!=xd&&document.addEventListener('ms'===xd?'MSFullscreen'+(a.charAt(0).toUpperCase()+a.slice(1)):xd+'fullscreen'+a,b)}
function Ed(a,b){A('Fullscreen enter requested');if(null==xd)return Promise.reject(Error('Browser does not support fullscreen API'));if(null==xd||!document[Bd('fullscreenEnabled')])return Promise.reject(Error('Browser is blocking fullscreen request'));if(a.is())return Promise.resolve();if(a.c&&'exit'===a.c.type)return Promise.reject(Error('Fullscreen exit in progress'));null==a.c&&(a.c={type:'enter'},a.c.tc=new Promise(function(d,e){A('Entering fullscreen');a.c.resolve=d;a.c.reject=e;b[Bd('requestFullscreen')]()}));
return a.c.tc}function Fd(a){A('Fullscreen exit requested');if(!a.is())return Promise.resolve();if(a.c&&'enter'===a.c.type)return Promise.reject(Error('Fullscreen enter in progress'));null==a.c&&(a.c={type:'exit'},a.c.tc=new Promise(function(b,d){A('Exiting fullscreen');a.c.resolve=b;a.c.reject=d;document[Bd('exitFullscreen')]()}));return a.c.tc};function Gd(a){var b=this;A('Initializing video');this.j=a;this.f=this.canvas=null;this.v='webgl';this.g='fceux';this.m=this.i=null;this.l=1;this.h='nearest';this.c=!1;this.s='maximized';this.L=new Cd;Dd('change',function(){b.canvas&&(A('Updating canvas after fullscreen change'),Hd(b),Id(b),Jd(b),b.aa())});this.j.Sb(sb(this.g));'https:'===location.protocol&&window.addEventListener('deviceorientation',function(){return Kd(b)});window.addEventListener('resize',function(){return Kd(b)})}
function Kd(a){a.mb()&&(A('Updating fullscreen canvas after resolution change'),Hd(a),Id(a),Jd(a),a.aa())}c=Gd.prototype;
c.yc=function(a){if(null!==a&&!(a instanceof HTMLCanvasElement))throw Error('Invalid video output: '+n(a));A('Setting video output to '+a);if(this.canvas=a){a:{a=this.v;var b=this.canvas;do{var d=ud[a];if(null==d)throw Error('Invalid renderer: '+n(a));try{A('Creating "'+a+'" renderer');var e=new d(b);break a}catch(h){y.error('Failed to create "'+a+'" renderer',h)}a=wd[a]}while(a);throw Error('Unable to create renderer');}this.f=e;this.i=this.f.kc(0,0,256,240);this.m=this.f.kc(256,0,256,240);Hd(this);
Id(this);Jd(this);this.aa()}};c.Z=function(){return this.canvas};function dd(a){return a.canvas?a.canvas.getBoundingClientRect():null}function cd(a,b,d){if(a.canvas){var e=dd(a);return[~~((b-e.left)/(e.width/(256*(a.c?2:1)))),~~((d-e.top)/(e.height/240))]}return null}function Id(a){a.canvas.width=256*Ld(a)*(a.c?2:1);a.canvas.height=240*Ld(a);A('Canvas resized to '+a.canvas.width+'x'+a.canvas.height+' px')}
function Jd(a){if(a.mb()){var b=a.canvas;a=a.s;A('Applying "'+a+'" style to canvas');var d=Object.assign(b.style,ld);'maximized'===a?b.width/b.height>window.innerWidth/window.innerHeight?d.width='100%':d.height='100%':'stretched'===a&&(d.width='100%',d.height='100%')}else for(b in a=a.canvas,A('Removing style from canvas'),a=a.style,ld)a.removeProperty(b)}
c.ke=function(a){if(!(a in ud))throw Error('Invalid video renderer: '+n(a));if(this.v!==a){if(this.canvas)throw Error('Cannot change video renderer once output is set');A('Using "'+a+'" video renderer');this.v=a}};c.ee=function(){return this.v};function Hd(a){a.f.Rb(a.h);a.f.Ub(Ld(a))}c.pb=function(){this.j.pb(this.i.data);this.c&&this.j.vc(this.m.data)};c.aa=function(){this.f.Gc();this.f.aa(this.i);this.c&&this.f.aa(this.m);this.f.end()};
c.Zd=function(){if(null==this.canvas)throw Error('No video output');this.i.data.fill(qb);this.c&&this.m.data.fill(qb);this.aa()};c.Sb=function(a){if(!(a in rb))throw Error('Invalid video palette: '+n(a));this.g!==a&&(A('Setting video palette to "'+a+'"'),this.g=a,this.j.Sb(sb(this.g)),this.canvas&&(this.pb(),this.aa()))};c.Wd=function(){return this.g};
c.Ub=function(a){if('number'!==typeof a||0>=a)throw Error('Invalid video scale: '+n(a));this.l!==a&&(A('Setting video scale to '+a),this.l=a,this.canvas&&(Hd(this),Id(this),Jd(this),this.aa()))};c.fe=function(){return this.l};function Ld(a){a.mb()?(a=Math.min(window.innerWidth/(256*(a.c?2:1)),window.innerHeight/240),a=1<a?~~a:a):a=a.l;return a}
c.Rb=function(a){if(!(0<=['nearest','linear'].indexOf(a)))throw Error('Invalid video filter: '+n(a));this.h!==a&&(A('Setting video filter to "'+a+'"'),this.h=a,this.canvas&&(Hd(this),this.aa()))};c.ce=function(){return this.h};c.ie=function(a){if('boolean'!==typeof a)throw Error('Invalid video debug: '+n(a));this.c!==a&&(A('Setting video debug to '+(a?'on':'off')),this.c=a,this.canvas&&(Hd(this),Id(this),Jd(this),this.pb(),this.aa()))};c.he=function(){return this.c};
c.ae=function(){if(null==this.canvas)throw Error('No video output');return Ed(this.L,this.canvas.parentElement)};c.Vd=function(){return Fd(this.L)};c.mb=function(){return this.L.is()};c.je=function(a){if(!(0<=kd.indexOf(a)))throw Error('Invalid fullscreen type: '+n(a));this.s!==a&&(A('Setting fullscreen type to "'+a+'"'),this.s=a,this.mb()&&Jd(this))};c.de=function(){return this.s};function Md(a){A('Downloading data from "'+a+'"');return new Promise(function(b,d){var e=new XMLHttpRequest;e.open('GET',a,!0);e.responseType='arraybuffer';e.onload=function(){200===e.status?b(e.response):0===e.status?d(Error('Failed to connect to the server')):d(Error('Failed to download data ('+e.status+' '+e.statusText+')'))};e.onerror=function(){d(Error('Failed to connect to the server'))};e.send()})}
function Nd(a){A('Reading contents of '+k(a.size)+' blob');return new Promise(function(b,d){if(10485760<a.size)d(Error('Input is too large ('+k(a.size)+')'));else{var e=new FileReader;e.onload=function(h){b(h.target.result)};e.onerror=function(h){d(Error(h.target.error||'Unknown error'))};e.readAsArrayBuffer(a)}})};function Od(a,b,d){A('Initializing ROM loader');this.c=a;this.g=b;this.h=d}Od.prototype.load=function(a){var b=this;if('string'===typeof a)return Md(a).then(function(d){return Pd(b,d)});if(a instanceof Blob)return Nd(a).then(function(d){return Pd(b,d)});if(a instanceof Array||a instanceof ArrayBuffer||a instanceof Uint8Array)return Pd(this,a);throw Error('Invalid source: '+n(a));};
function Pd(a,b){b instanceof Uint8Array||(b=new Uint8Array(b));return Qd(a,b).then(function(d){a:{A('Creating cartridge from ROM image');if(!(d instanceof Uint8Array))throw Error('Invalid ROM image: '+n(d));A('Parsing '+k(d.length)+' of data');for(var e=f(sc),h=e.next();!h.done;h=e.next())if(h=h.value,h.supports(d)){A('Using "'+h.name+'" parser');d=h.parse(d);var l;A('Computing SHA-1');e=new Uint8Array(d.xa+d.Ua);e.set(d.Qa);d.ib&&e.set(d.ib,d.xa);h=e.length;var m=Array(17),p=0,r=0,q=0,F=0,K=!1,
G=1732584193,O=4023233417,I=2562383102,L=271733878,V=3285377520;do{m[0]=p;m.fill(0,1,17);for(l=q;r<h&&64>l;r++)m[l>>2]|=e[r]<<uc[l++&3];F+=l-q;q=l-64;r===h&&(m[l>>2]|=tc[l&3],r++);p=m[16];r>h&&56>l&&(m[15]=F<<3,K=!0);for(l=16;80>l;l++){var z=m[l-3]^m[l-8]^m[l-14]^m[l-16];m[l]=z<<1|z>>>31}var t=G,u=O,v=I,w=L,x=V;for(l=0;20>l;l+=5){var C=u&v|~u&w;z=t<<5|t>>>27;x=z+C+x+1518500249+m[l]<<0;u=u<<30|u>>>2;C=t&u|~t&v;z=x<<5|x>>>27;w=z+C+w+1518500249+m[l+1]<<0;t=t<<30|t>>>2;C=x&t|~x&u;z=w<<5|w>>>27;v=z+C+
v+1518500249+m[l+2]<<0;x=x<<30|x>>>2;C=w&x|~w&t;z=v<<5|v>>>27;u=z+C+u+1518500249+m[l+3]<<0;w=w<<30|w>>>2;C=v&w|~v&x;z=u<<5|u>>>27;t=z+C+t+1518500249+m[l+4]<<0;v=v<<30|v>>>2}for(;40>l;l+=5)C=u^v^w,z=t<<5|t>>>27,x=z+C+x+1859775393+m[l]<<0,u=u<<30|u>>>2,C=t^u^v,z=x<<5|x>>>27,w=z+C+w+1859775393+m[l+1]<<0,t=t<<30|t>>>2,C=x^t^u,z=w<<5|w>>>27,v=z+C+v+1859775393+m[l+2]<<0,x=x<<30|x>>>2,C=w^x^t,z=v<<5|v>>>27,u=z+C+u+1859775393+m[l+3]<<0,w=w<<30|w>>>2,C=v^w^x,z=u<<5|u>>>27,t=z+C+t+1859775393+m[l+4]<<0,v=v<<
30|v>>>2;for(;60>l;l+=5)C=u&v|u&w|v&w,z=t<<5|t>>>27,x=z+C+x-1894007588+m[l]<<0,u=u<<30|u>>>2,C=t&u|t&v|u&v,z=x<<5|x>>>27,w=z+C+w-1894007588+m[l+1]<<0,t=t<<30|t>>>2,C=x&t|x&u|t&u,z=w<<5|w>>>27,v=z+C+v-1894007588+m[l+2]<<0,x=x<<30|x>>>2,C=w&x|w&t|x&t,z=v<<5|v>>>27,u=z+C+u-1894007588+m[l+3]<<0,w=w<<30|w>>>2,C=v&w|v&x|w&x,z=u<<5|u>>>27,t=z+C+t-1894007588+m[l+4]<<0,v=v<<30|v>>>2;for(;80>l;l+=5)C=u^v^w,z=t<<5|t>>>27,x=z+C+x-899497514+m[l]<<0,u=u<<30|u>>>2,C=t^u^v,z=x<<5|x>>>27,w=z+C+w-899497514+m[l+1]<<
0,t=t<<30|t>>>2,C=x^t^u,z=w<<5|w>>>27,v=z+C+v-899497514+m[l+2]<<0,x=x<<30|x>>>2,C=w^x^t,z=v<<5|v>>>27,u=z+C+u-899497514+m[l+3]<<0,w=w<<30|w>>>2,C=v^w^x,z=u<<5|u>>>27,t=z+C+t-899497514+m[l+4]<<0,v=v<<30|v>>>2;G=G+t<<0;O=O+u<<0;I=I+v<<0;L=L+w<<0;V=V+x<<0}while(!K);d.Zc=W[G>>28&15]+W[G>>24&15]+W[G>>20&15]+W[G>>16&15]+W[G>>12&15]+W[G>>8&15]+W[G>>4&15]+W[G&15]+W[O>>28&15]+W[O>>24&15]+W[O>>20&15]+W[O>>16&15]+W[O>>12&15]+W[O>>8&15]+W[O>>4&15]+W[O&15]+W[I>>28&15]+W[I>>24&15]+W[I>>20&15]+W[I>>16&15]+W[I>>
12&15]+W[I>>8&15]+W[I>>4&15]+W[I&15]+W[L>>28&15]+W[L>>24&15]+W[L>>20&15]+W[L>>16&15]+W[L>>12&15]+W[L>>8&15]+W[L>>4&15]+W[L&15]+W[V>>28&15]+W[V>>24&15]+W[V>>20&15]+W[V>>16&15]+W[V>>12&15]+W[V>>8&15]+W[V>>4&15]+W[V&15];A('==========[Cartridge Info - Start]==========');A('SHA-1                 : '+d.Zc);A('Mapper                : '+d.M);A('Submapper             : '+d.le);A('Region                : '+d.region);A('Mirroring             : '+d.nb);A('PRG ROM size          : '+k(d.xa));A('PRG RAM size          : '+
k(d.ob));A('PRG RAM size (battery): '+k(d.Qb));A('CHR ROM size          : '+k(d.Ua));A('CHR RAM size          : '+k(d.hb));A('CHR RAM size (battery): '+k(d.Jb));A('==========[Cartridge Info - End]==========');break a}throw Error('Unknown ROM image format');}jc(a.c,d);a.g.Na()&&(d=a.g,d.eb(),d.start())})}
function Qd(a,b){if(80===b[0]&&75===b[1]&&3===b[2]&&4===b[3]){A('Extracting ROM image from '+k(b.length)+' ZIP archive');a=a.h;if(null==a||null==a.loadAsync)throw Error('Unable to extract ROM image: JSZip 3 is not available');return a.loadAsync(b).then(function(d){d=d.file(/^.*\.nes$/i);if(0===d.length)throw Error('ZIP archive does not contain ".nes" ROM image');return d[0].async('uint8array')})}return Promise.resolve(b)}Od.prototype.j=function(){this.f()&&(A('Unloading ROM image'),jc(this.c,null))};
Od.prototype.f=function(){return null!=this.c.ja};Od.prototype.i=function(){var a=this.c.ja;return a?a.Zc:null};function Rd(a){var b={},d;for(d in a){var e=Object.getOwnPropertyDescriptor(a,d);if(e.enumerable){var h=a[d];e.writable||e.set?b[d]=h:'object'===typeof h&&(b[d]=Rd(h))}}return b};function Sd(a,b){for(var d in b)if(d in a){var e=b[d];if(void 0!==e){var h=Object.getOwnPropertyDescriptor(a,d);h.enumerable&&(h.writable||h.set?a[d]=e:'object'===typeof e&&Sd(a[d],e))}}};function Td(a,b){for(var d=[],e=1;e<arguments.length;++e)d[e-1]=arguments[e];return{get:Ud.apply(null,[a].concat(ca(d)))}}function Y(a,b,d){for(var e=[],h=2;h<arguments.length;++h)e[h-2]=arguments[h];return{get:Ud.apply(null,[a].concat(ca(e))),set:Ud.apply(null,[b].concat(ca(e))),enumerable:!0}}function Vd(a,b,d){for(var e=[],h=2;h<arguments.length;++h)e[h-2]=arguments[h];return{get:Ud.apply(null,[a].concat(ca(e))),set:Ud.apply(null,[b].concat(ca(e)))}}
function Z(a,b){for(var d=[],e=1;e<arguments.length;++e)d[e-1]=arguments[e];return{value:Ud.apply(null,[a].concat(ca(d)))}}function Wd(a){return{value:Object.defineProperties({},a),enumerable:!0}}function Xd(a,b,d,e){for(var h=[],l=3;l<arguments.length;++l)h[l-3]=arguments[l];l=f(h);h=l.next().value;l=ba(l);for(var m={},p=f(a),r=p.next();!r.done;r=p.next())r=r.value,m[r]=Y.apply(null,[b,d,h,r].concat(ca(l)));return Wd(m)}
function Ud(a,b){for(var d=[],e=1;e<arguments.length;++e)d[e-1]=arguments[e];return d.length?a.bind.apply(a,ca(d)):a};var Yd=Object.defineProperties;
function Zd(a){function b(K){Sd(F,K);'inputs'in K&&ad(p,K.inputs)}a=void 0===a?{}:a;if(!a||'object'!==typeof a)throw Error('Invalid initialization options: '+n(a));var d=a.JSZip||window.JSZip,e=new gc,h=new Gd(e),l=null!=wc?new Bc(e):null,m=new Zc(e),p=new $c,r=new bd(p,m,h);r=new Rc(r);var q=new jd(e,h,l,r);d=new Od(e,q,d);var F=Yd({},{running:Td(q.Na,q),fps:Td(q.be,q),region:Y(q.Md,q.Tb,q),speed:Y(q.Nd,q.rb,q),start:Z(q.start,q),stop:Z(q.eb,q),step:Z(q.step,q),power:Z(q.Ob,q),reset:Z(q.reset,q),
nvram:Td(e.qc,e),use:Z(b),rom:Wd({loaded:Td(d.f,d),sha1:Td(d.i,d),load:Z(d.load,d),unload:Z(d.j,d)}),video:Wd({output:Vd(h.Z,h.yc,h),renderer:Y(h.ee,h.ke,h),palette:Y(h.Wd,h.Sb,h),scale:Y(h.fe,h.Ub,h),filter:Y(h.ce,h.Rb,h),debug:Y(h.he,h.ie,h),clear:Z(h.Zd,h)}),fullscreen:Wd({type:Y(h.de,h.je,h),is:Td(h.mb,h),enter:Z(h.ae,h),exit:Z(h.Vd,h)}),audio:l?Wd({enabled:Y(l.ed,l.fd,l),volume:Xd(Object.keys(zc),l.Wa,l.sb,l)}):{value:null},devices:Xd(Dc,m.get,m.set,m),inputs:Wd({state:Wd({get:Z(m.Va,m),set:Z(m.Ya,
m)}),map:Wd({get:Z(p.get,p),set:Z(p.set,p),'delete':Z(p.yd,p)}),record:Z(r.i,r)}),config:Wd({get:Z(function(){for(var K=Rd(F),G={},O=f(p.c),I=O.next();!I.done;I=O.next()){var L=I.value;I=L.jb.toString();L=L.tb.toString();G[I]=G[I]||[];G[I].push(L)}K.inputs=G;return K}),use:Z(b)}),toString:Z(function(){return'cfxnes 0.7.0'})});b(a);(e=a.video)&&'output'in e?h.yc(e.output):(e=document.getElementById('cfxnes'),e instanceof HTMLCanvasElement&&h.yc(e));'inputs'in a||ad(p,{'1.joypad.a':'keyboard.x','1.joypad.b':['keyboard.y',
'keyboard.z'],'1.joypad.start':'keyboard.enter','1.joypad.select':'keyboard.shift','1.joypad.up':'keyboard.up','1.joypad.down':'keyboard.down','1.joypad.left':'keyboard.left','1.joypad.right':'keyboard.right','2.zapper.trigger':'mouse.left'});'rom'in a&&d.load(a.rom).then(function(){return q.start()}).catch(function(K){y.error('Failed to load ROM',K)});return F}y.g('warn');try{Yd(Zd,{name:{value:'cfxnes'}})}catch(a){ua('Unable to redefine cfxnes.name property: running in pre-ES2015 environment')}
Yd(Zd,{version:{value:'0.7.0'},logLevel:Y(y.h,y.g,y),close:{value:function(){if(null==vc)return Promise.resolve();var a=vc.close();vc=void 0;return a}}});'undefined'!==typeof root&&(root.cfxnes=Zd);
  // Compiler output [end]
  return root;
}.bind(this)));

//# sourceMappingURL=cfxnes.js.map
